/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { AccountRequestTracerRequestTraceErrors, AccountRequestTracerRequestTraceResponses, RequestTracerIdentifier } from '../types.gen';
import { zAccountRequestTracerRequestTraceBody, zAccountRequestTracerRequestTracePath, zAccountRequestTracerRequestTraceResponse } from '../zod.gen';

export class AccountRequestTracerService {
    /**
     * Request Trace
     */
    public static accountRequestTracerRequestTrace<ThrowOnError extends boolean = true>(parameters: {
        account_id: RequestTracerIdentifier;
        body?: {
            /**
             * Base64 encoded request body
             */
            base64?: string;
            /**
             * Arbitrary json as request body
             */
            json?: {
                [key: string]: unknown;
            };
            /**
             * Request body as plain text
             */
            plain_text?: string;
        };
        context?: {
            /**
             * Bot score used for evaluating tracing request processing
             */
            bot_score?: number;
            /**
             * Geodata for tracing request
             */
            geoloc?: {
                city?: string;
                continent?: string;
                is_eu_country?: boolean;
                iso_code?: string;
                latitude?: number;
                longitude?: number;
                postal_code?: string;
                region_code?: string;
                subdivision_2_iso_code?: string;
                timezone?: string;
            };
            /**
             * Whether to skip any challenges for tracing request (e.g.: captcha)
             */
            skip_challenge?: boolean;
            /**
             * Threat score used for evaluating tracing request processing
             */
            threat_score?: number;
        };
        cookies?: {
            [key: string]: string;
        };
        headers?: {
            [key: string]: string;
        };
        method: string;
        protocol?: string;
        skip_response?: boolean;
        url: string;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'account_id' },
                    { in: 'body', key: 'body' },
                    { in: 'body', key: 'context' },
                    { in: 'body', key: 'cookies' },
                    { in: 'body', key: 'headers' },
                    { in: 'body', key: 'method' },
                    { in: 'body', key: 'protocol' },
                    { in: 'body', key: 'skip_response' },
                    { in: 'body', key: 'url' }
                ] }]);
        return (options?.client ?? client).post<AccountRequestTracerRequestTraceResponses, AccountRequestTracerRequestTraceErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zAccountRequestTracerRequestTraceBody,
                path: zAccountRequestTracerRequestTracePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zAccountRequestTracerRequestTraceResponse.parseAsync(data),
            security: [{ name: 'X-Auth-Email', type: 'apiKey' }, { name: 'X-Auth-Key', type: 'apiKey' }],
            url: '/accounts/{account_id}/request-tracer/trace',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
}
