/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { AccountLoadBalancerSearchSearchResourcesErrors, AccountLoadBalancerSearchSearchResourcesResponses, LoadBalancingComponentsSchemasIdentifier } from '../types.gen';
import { zAccountLoadBalancerSearchSearchResourcesPath, zAccountLoadBalancerSearchSearchResourcesQuery, zAccountLoadBalancerSearchSearchResourcesResponse } from '../zod.gen';

export class AccountLoadBalancerSearchService {
    /**
     * Search Resources
     *
     * Search for Load Balancing resources.
     */
    public static accountLoadBalancerSearchSearchResources<ThrowOnError extends boolean = true>(parameters: {
        account_id: LoadBalancingComponentsSchemasIdentifier;
        query?: string;
        references?: '' | '*' | 'referral' | 'referrer';
        page?: number;
        per_page?: number;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'account_id' },
                    { in: 'query', key: 'query' },
                    { in: 'query', key: 'references' },
                    { in: 'query', key: 'page' },
                    { in: 'query', key: 'per_page' }
                ] }]);
        return (options?.client ?? client).get<AccountLoadBalancerSearchSearchResourcesResponses, AccountLoadBalancerSearchSearchResourcesErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zAccountLoadBalancerSearchSearchResourcesPath,
                query: zAccountLoadBalancerSearchSearchResourcesQuery.optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zAccountLoadBalancerSearchSearchResourcesResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/accounts/{account_id}/load_balancers/search',
            ...options,
            ...params
        });
    }
}
