/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { AiSearchCreateNamespaceErrors, AiSearchCreateNamespaceResponses, AiSearchDeleteNamespaceErrors, AiSearchDeleteNamespaceResponses, AiSearchFetchNamespaceErrors, AiSearchFetchNamespaceResponses, AiSearchListNamespacesErrors, AiSearchListNamespacesResponses, AiSearchMoveInstanceErrors, AiSearchMoveInstanceResponses, AiSearchUpdateNamespaceErrors, AiSearchUpdateNamespaceResponses } from '../types.gen';
import { zAiSearchCreateNamespaceBody, zAiSearchCreateNamespacePath, zAiSearchCreateNamespaceResponse, zAiSearchDeleteNamespacePath, zAiSearchDeleteNamespaceResponse, zAiSearchFetchNamespacePath, zAiSearchFetchNamespaceResponse, zAiSearchListNamespacesPath, zAiSearchListNamespacesQuery, zAiSearchListNamespacesResponse, zAiSearchMoveInstanceBody, zAiSearchMoveInstancePath, zAiSearchMoveInstanceResponse, zAiSearchUpdateNamespaceBody, zAiSearchUpdateNamespacePath, zAiSearchUpdateNamespaceResponse } from '../zod.gen';

export class AiSearchNamespacesService {
    /**
     * List namespaces.
     *
     * List namespaces.
     */
    public static aiSearchListNamespaces<ThrowOnError extends boolean = true>(parameters: {
        account_id: string;
        page?: number;
        per_page?: number;
        search?: string;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'account_id' },
                    { in: 'query', key: 'page' },
                    { in: 'query', key: 'per_page' },
                    { in: 'query', key: 'search' }
                ] }]);
        return (options?.client ?? client).get<AiSearchListNamespacesResponses, AiSearchListNamespacesErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zAiSearchListNamespacesPath,
                query: zAiSearchListNamespacesQuery.optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zAiSearchListNamespacesResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/accounts/{account_id}/ai-search/namespaces',
            ...options,
            ...params
        });
    }
    
    /**
     * Create namespace.
     *
     * Create a new namespace.
     */
    public static aiSearchCreateNamespace<ThrowOnError extends boolean = true>(parameters: {
        account_id: string;
        description?: string | null;
        name: string;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'account_id' },
                    { in: 'body', key: 'description' },
                    { in: 'body', key: 'name' }
                ] }]);
        return (options?.client ?? client).post<AiSearchCreateNamespaceResponses, AiSearchCreateNamespaceErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zAiSearchCreateNamespaceBody.optional(),
                path: zAiSearchCreateNamespacePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zAiSearchCreateNamespaceResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/accounts/{account_id}/ai-search/namespaces',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Delete namespace.
     *
     * Delete namespace.
     */
    public static aiSearchDeleteNamespace<ThrowOnError extends boolean = true>(parameters: {
        account_id: string;
        name: string;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'account_id' }, { in: 'path', key: 'name' }] }]);
        return (options?.client ?? client).delete<AiSearchDeleteNamespaceResponses, AiSearchDeleteNamespaceErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zAiSearchDeleteNamespacePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zAiSearchDeleteNamespaceResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/accounts/{account_id}/ai-search/namespaces/{name}',
            ...options,
            ...params
        });
    }
    
    /**
     * Read namespace.
     *
     * Read namespace.
     */
    public static aiSearchFetchNamespace<ThrowOnError extends boolean = true>(parameters: {
        account_id: string;
        name: string;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'account_id' }, { in: 'path', key: 'name' }] }]);
        return (options?.client ?? client).get<AiSearchFetchNamespaceResponses, AiSearchFetchNamespaceErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zAiSearchFetchNamespacePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zAiSearchFetchNamespaceResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/accounts/{account_id}/ai-search/namespaces/{name}',
            ...options,
            ...params
        });
    }
    
    /**
     * Update namespace.
     *
     * Update namespace.
     */
    public static aiSearchUpdateNamespace<ThrowOnError extends boolean = true>(parameters: {
        account_id: string;
        name: string;
        description?: string | null;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'account_id' },
                    { in: 'path', key: 'name' },
                    { in: 'body', key: 'description' }
                ] }]);
        return (options?.client ?? client).put<AiSearchUpdateNamespaceResponses, AiSearchUpdateNamespaceErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zAiSearchUpdateNamespaceBody.optional(),
                path: zAiSearchUpdateNamespacePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zAiSearchUpdateNamespaceResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/accounts/{account_id}/ai-search/namespaces/{name}',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Move an instance to a different namespace.
     *
     * Moves an instance from its current namespace to the specified target namespace. Use 'default' as new_namespace to move the instance back to the default namespace. Fails with 400 if the target namespace already has an instance with the same id (ids must be unique within a namespace — the same id can exist in different namespaces).
     */
    public static aiSearchMoveInstance<ThrowOnError extends boolean = true>(parameters: {
        account_id: string;
        name: string;
        id: string;
        new_namespace: string;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'account_id' },
                    { in: 'path', key: 'name' },
                    { in: 'path', key: 'id' },
                    { in: 'body', key: 'new_namespace' }
                ] }]);
        return (options?.client ?? client).patch<AiSearchMoveInstanceResponses, AiSearchMoveInstanceErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zAiSearchMoveInstanceBody.optional(),
                path: zAiSearchMoveInstancePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zAiSearchMoveInstanceResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/accounts/{account_id}/ai-search/namespaces/{name}/instances/{id}',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
}
