/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { ClientCertificateForAZoneClientCertificateDetailsErrors, ClientCertificateForAZoneClientCertificateDetailsResponses, ClientCertificateForAZoneCreateClientCertificateErrors, ClientCertificateForAZoneCreateClientCertificateResponses, ClientCertificateForAZoneDeleteClientCertificateErrors, ClientCertificateForAZoneDeleteClientCertificateResponses, ClientCertificateForAZoneEditClientCertificateErrors, ClientCertificateForAZoneEditClientCertificateResponses, ClientCertificateForAZoneListClientCertificatesErrors, ClientCertificateForAZoneListClientCertificatesResponses, ClientCertificateForAZoneListHostnameAssociationsErrors, ClientCertificateForAZoneListHostnameAssociationsResponses, ClientCertificateForAZonePutHostnameAssociationsErrors, ClientCertificateForAZonePutHostnameAssociationsResponses, TlsCertificatesAndHostnamesHostnameAssociation, TlsCertificatesAndHostnamesIdentifier, TlsCertificatesAndHostnamesSchemasCsr, TlsCertificatesAndHostnamesSchemasValidityDays } from '../types.gen';
import { zClientCertificateForAZoneClientCertificateDetailsPath, zClientCertificateForAZoneClientCertificateDetailsResponse, zClientCertificateForAZoneCreateClientCertificateBody, zClientCertificateForAZoneCreateClientCertificatePath, zClientCertificateForAZoneCreateClientCertificateResponse, zClientCertificateForAZoneDeleteClientCertificatePath, zClientCertificateForAZoneDeleteClientCertificateResponse, zClientCertificateForAZoneEditClientCertificateBody, zClientCertificateForAZoneEditClientCertificatePath, zClientCertificateForAZoneEditClientCertificateResponse, zClientCertificateForAZoneListClientCertificatesPath, zClientCertificateForAZoneListClientCertificatesQuery, zClientCertificateForAZoneListClientCertificatesResponse, zClientCertificateForAZoneListHostnameAssociationsPath, zClientCertificateForAZoneListHostnameAssociationsQuery, zClientCertificateForAZoneListHostnameAssociationsResponse, zClientCertificateForAZonePutHostnameAssociationsBody, zClientCertificateForAZonePutHostnameAssociationsPath, zClientCertificateForAZonePutHostnameAssociationsResponse } from '../zod.gen';

export class ApiShieldClientCertificatesForAZoneService {
    /**
     * List Hostname Associations
     *
     * List Hostname Associations
     */
    public static clientCertificateForAZoneListHostnameAssociations<ThrowOnError extends boolean = true>(parameters: {
        zone_id: TlsCertificatesAndHostnamesIdentifier;
        mtls_certificate_id?: string;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }, { in: 'query', key: 'mtls_certificate_id' }] }]);
        return (options?.client ?? client).get<ClientCertificateForAZoneListHostnameAssociationsResponses, ClientCertificateForAZoneListHostnameAssociationsErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zClientCertificateForAZoneListHostnameAssociationsPath,
                query: zClientCertificateForAZoneListHostnameAssociationsQuery.optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zClientCertificateForAZoneListHostnameAssociationsResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/zones/{zone_id}/certificate_authorities/hostname_associations',
            ...options,
            ...params
        });
    }
    
    /**
     * Replace Hostname Associations
     *
     * Replace Hostname Associations
     */
    public static clientCertificateForAZonePutHostnameAssociations<ThrowOnError extends boolean = true>(parameters: {
        zone_id: TlsCertificatesAndHostnamesIdentifier;
        tlsCertificatesAndHostnamesHostnameAssociation: TlsCertificatesAndHostnamesHostnameAssociation;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }, { key: 'tlsCertificatesAndHostnamesHostnameAssociation', map: 'body' }] }]);
        return (options?.client ?? client).put<ClientCertificateForAZonePutHostnameAssociationsResponses, ClientCertificateForAZonePutHostnameAssociationsErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zClientCertificateForAZonePutHostnameAssociationsBody,
                path: zClientCertificateForAZonePutHostnameAssociationsPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zClientCertificateForAZonePutHostnameAssociationsResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/zones/{zone_id}/certificate_authorities/hostname_associations',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * List Client Certificates
     *
     * List all of your Zone's API Shield mTLS Client Certificates by Status and/or using Pagination
     */
    public static clientCertificateForAZoneListClientCertificates<ThrowOnError extends boolean = true>(parameters: {
        zone_id: TlsCertificatesAndHostnamesIdentifier;
        status?: 'all' | 'active' | 'pending_reactivation' | 'pending_revocation' | 'revoked';
        page?: number;
        per_page?: number;
        limit?: number;
        offset?: number;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'zone_id' },
                    { in: 'query', key: 'status' },
                    { in: 'query', key: 'page' },
                    { in: 'query', key: 'per_page' },
                    { in: 'query', key: 'limit' },
                    { in: 'query', key: 'offset' }
                ] }]);
        return (options?.client ?? client).get<ClientCertificateForAZoneListClientCertificatesResponses, ClientCertificateForAZoneListClientCertificatesErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zClientCertificateForAZoneListClientCertificatesPath,
                query: zClientCertificateForAZoneListClientCertificatesQuery.optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zClientCertificateForAZoneListClientCertificatesResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/zones/{zone_id}/client_certificates',
            ...options,
            ...params
        });
    }
    
    /**
     * Create Client Certificate
     *
     * Create a new API Shield mTLS Client Certificate
     */
    public static clientCertificateForAZoneCreateClientCertificate<ThrowOnError extends boolean = true>(parameters: {
        zone_id: TlsCertificatesAndHostnamesIdentifier;
        csr: TlsCertificatesAndHostnamesSchemasCsr;
        validity_days: TlsCertificatesAndHostnamesSchemasValidityDays;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'zone_id' },
                    { in: 'body', key: 'csr' },
                    { in: 'body', key: 'validity_days' }
                ] }]);
        return (options?.client ?? client).post<ClientCertificateForAZoneCreateClientCertificateResponses, ClientCertificateForAZoneCreateClientCertificateErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zClientCertificateForAZoneCreateClientCertificateBody,
                path: zClientCertificateForAZoneCreateClientCertificatePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zClientCertificateForAZoneCreateClientCertificateResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/zones/{zone_id}/client_certificates',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Revoke Client Certificate
     *
     * Set a API Shield mTLS Client Certificate to pending_revocation status for processing to revoked status.
     */
    public static clientCertificateForAZoneDeleteClientCertificate<ThrowOnError extends boolean = true>(parameters: {
        zone_id: TlsCertificatesAndHostnamesIdentifier;
        client_certificate_id: TlsCertificatesAndHostnamesIdentifier;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }, { in: 'path', key: 'client_certificate_id' }] }]);
        return (options?.client ?? client).delete<ClientCertificateForAZoneDeleteClientCertificateResponses, ClientCertificateForAZoneDeleteClientCertificateErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zClientCertificateForAZoneDeleteClientCertificatePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zClientCertificateForAZoneDeleteClientCertificateResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/zones/{zone_id}/client_certificates/{client_certificate_id}',
            ...options,
            ...params
        });
    }
    
    /**
     * Client Certificate Details
     *
     * Get Details for a single mTLS API Shield Client Certificate
     */
    public static clientCertificateForAZoneClientCertificateDetails<ThrowOnError extends boolean = true>(parameters: {
        zone_id: TlsCertificatesAndHostnamesIdentifier;
        client_certificate_id: TlsCertificatesAndHostnamesIdentifier;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }, { in: 'path', key: 'client_certificate_id' }] }]);
        return (options?.client ?? client).get<ClientCertificateForAZoneClientCertificateDetailsResponses, ClientCertificateForAZoneClientCertificateDetailsErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zClientCertificateForAZoneClientCertificateDetailsPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zClientCertificateForAZoneClientCertificateDetailsResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/zones/{zone_id}/client_certificates/{client_certificate_id}',
            ...options,
            ...params
        });
    }
    
    /**
     * Reactivate Client Certificate
     *
     * If a API Shield mTLS Client Certificate is in a pending_revocation state, you may reactivate it with this endpoint.
     */
    public static clientCertificateForAZoneEditClientCertificate<ThrowOnError extends boolean = true>(parameters: {
        zone_id: TlsCertificatesAndHostnamesIdentifier;
        client_certificate_id: TlsCertificatesAndHostnamesIdentifier;
        reactivate?: boolean;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'zone_id' },
                    { in: 'path', key: 'client_certificate_id' },
                    { in: 'body', key: 'reactivate' }
                ] }]);
        return (options?.client ?? client).patch<ClientCertificateForAZoneEditClientCertificateResponses, ClientCertificateForAZoneEditClientCertificateErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zClientCertificateForAZoneEditClientCertificateBody,
                path: zClientCertificateForAZoneEditClientCertificatePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zClientCertificateForAZoneEditClientCertificateResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/zones/{zone_id}/client_certificates/{client_certificate_id}',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
}
