/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { AutoragConfigFilesErrors, AutoragConfigFilesResponses, AutoragConfigSyncErrors, AutoragConfigSyncResponses } from '../types.gen';
import { zAutoragConfigFilesPath, zAutoragConfigFilesQuery, zAutoragConfigFilesResponse, zAutoragConfigSyncPath, zAutoragConfigSyncResponse } from '../zod.gen';

export class AutoRagRagService {
    /**
     * Files
     */
    public static autoragConfigFiles<ThrowOnError extends boolean = true>(parameters: {
        id: string;
        account_id: string;
        page?: number;
        per_page?: number;
        search?: string;
        status?: 'completed' | 'queued' | 'running' | 'error';
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'id' },
                    { in: 'path', key: 'account_id' },
                    { in: 'query', key: 'page' },
                    { in: 'query', key: 'per_page' },
                    { in: 'query', key: 'search' },
                    { in: 'query', key: 'status' }
                ] }]);
        return (options?.client ?? client).get<AutoragConfigFilesResponses, AutoragConfigFilesErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zAutoragConfigFilesPath,
                query: zAutoragConfigFilesQuery.optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zAutoragConfigFilesResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/accounts/{account_id}/autorag/rags/{id}/files',
            ...options,
            ...params
        });
    }
    
    /**
     * Sync
     */
    public static autoragConfigSync<ThrowOnError extends boolean = true>(parameters: {
        id: string;
        account_id: string;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'id' }, { in: 'path', key: 'account_id' }] }]);
        return (options?.client ?? client).patch<AutoragConfigSyncResponses, AutoragConfigSyncErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zAutoragConfigSyncPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zAutoragConfigSyncResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/accounts/{account_id}/autorag/rags/{id}/sync',
            ...options,
            ...params
        });
    }
}
