/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams, type RequestResult } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { CloudflareTunnelConfigurationGetConfigurationErrors, CloudflareTunnelConfigurationGetConfigurationResponses, CloudflareTunnelConfigurationGetWarpConnectorConfigurationErrors, CloudflareTunnelConfigurationGetWarpConnectorConfigurationResponses, CloudflareTunnelConfigurationPutConfigurationErrors, CloudflareTunnelConfigurationPutConfigurationResponses, CloudflareTunnelConfigurationUpdateWarpConnectorConfigurationErrors, CloudflareTunnelConfigurationUpdateWarpConnectorConfigurationResponses, TunnelConfigWritable, TunnelIdentifier, TunnelMeshConfigurationRequestBody, TunnelTunnelId2 } from '../types.gen';
import { zCloudflareTunnelConfigurationGetConfigurationPath, zCloudflareTunnelConfigurationGetConfigurationResponse, zCloudflareTunnelConfigurationGetWarpConnectorConfigurationPath, zCloudflareTunnelConfigurationGetWarpConnectorConfigurationResponse, zCloudflareTunnelConfigurationPutConfigurationBody, zCloudflareTunnelConfigurationPutConfigurationPath, zCloudflareTunnelConfigurationPutConfigurationResponse, zCloudflareTunnelConfigurationUpdateWarpConnectorConfigurationBody, zCloudflareTunnelConfigurationUpdateWarpConnectorConfigurationPath, zCloudflareTunnelConfigurationUpdateWarpConnectorConfigurationResponse } from '../zod.gen';

export class CloudflareTunnelConfigurationService {
    /**
     * Get configuration
     *
     * Gets the configuration for a remotely-managed tunnel
     */
    public static cloudflareTunnelConfigurationGetConfiguration<ThrowOnError extends boolean = true>(parameters: {
        account_id: TunnelIdentifier;
        tunnel_id: TunnelTunnelId2;
    }, options?: Options<never, ThrowOnError>): RequestResult<CloudflareTunnelConfigurationGetConfigurationResponses, CloudflareTunnelConfigurationGetConfigurationErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'account_id' }, { in: 'path', key: 'tunnel_id' }] }]);
        return (options?.client ?? client).get<CloudflareTunnelConfigurationGetConfigurationResponses, CloudflareTunnelConfigurationGetConfigurationErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zCloudflareTunnelConfigurationGetConfigurationPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zCloudflareTunnelConfigurationGetConfigurationResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-User-Service-Key', type: 'apiKey' }
            ],
            url: '/accounts/{account_id}/cfd_tunnel/{tunnel_id}/configurations',
            ...options,
            ...params
        });
    }
    
    /**
     * Put configuration
     *
     * Adds or updates the configuration for a remotely-managed tunnel.
     */
    public static cloudflareTunnelConfigurationPutConfiguration<ThrowOnError extends boolean = true>(parameters: {
        account_id: TunnelIdentifier;
        tunnel_id: TunnelTunnelId2;
        config?: TunnelConfigWritable;
    }, options?: Options<never, ThrowOnError>): RequestResult<CloudflareTunnelConfigurationPutConfigurationResponses, CloudflareTunnelConfigurationPutConfigurationErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'account_id' },
                    { in: 'path', key: 'tunnel_id' },
                    { in: 'body', key: 'config' }
                ] }]);
        return (options?.client ?? client).put<CloudflareTunnelConfigurationPutConfigurationResponses, CloudflareTunnelConfigurationPutConfigurationErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zCloudflareTunnelConfigurationPutConfigurationBody,
                path: zCloudflareTunnelConfigurationPutConfigurationPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zCloudflareTunnelConfigurationPutConfigurationResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-User-Service-Key', type: 'apiKey' }
            ],
            url: '/accounts/{account_id}/cfd_tunnel/{tunnel_id}/configurations',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Get WARP Connector HA configuration
     *
     * Gets the high-availability configuration for a WARP Connector tunnel.
     */
    public static cloudflareTunnelConfigurationGetWarpConnectorConfiguration<ThrowOnError extends boolean = true>(parameters: {
        account_id: TunnelIdentifier;
        tunnel_id: TunnelTunnelId2;
    }, options?: Options<never, ThrowOnError>): RequestResult<CloudflareTunnelConfigurationGetWarpConnectorConfigurationResponses, CloudflareTunnelConfigurationGetWarpConnectorConfigurationErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'account_id' }, { in: 'path', key: 'tunnel_id' }] }]);
        return (options?.client ?? client).get<CloudflareTunnelConfigurationGetWarpConnectorConfigurationResponses, CloudflareTunnelConfigurationGetWarpConnectorConfigurationErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zCloudflareTunnelConfigurationGetWarpConnectorConfigurationPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zCloudflareTunnelConfigurationGetWarpConnectorConfigurationResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-User-Service-Key', type: 'apiKey' }
            ],
            url: '/accounts/{account_id}/warp_connector/{tunnel_id}/configurations',
            ...options,
            ...params
        });
    }
    
    /**
     * Update WARP Connector HA configuration
     *
     * Adds or updates the high-availability configuration for a WARP Connector tunnel.
     */
    public static cloudflareTunnelConfigurationUpdateWarpConnectorConfiguration<ThrowOnError extends boolean = true>(parameters: {
        account_id: TunnelIdentifier;
        tunnel_id: TunnelTunnelId2;
        tunnelMeshConfigurationRequestBody: TunnelMeshConfigurationRequestBody;
    }, options?: Options<never, ThrowOnError>): RequestResult<CloudflareTunnelConfigurationUpdateWarpConnectorConfigurationResponses, CloudflareTunnelConfigurationUpdateWarpConnectorConfigurationErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'account_id' },
                    { in: 'path', key: 'tunnel_id' },
                    { key: 'tunnelMeshConfigurationRequestBody', map: 'body' }
                ] }]);
        return (options?.client ?? client).put<CloudflareTunnelConfigurationUpdateWarpConnectorConfigurationResponses, CloudflareTunnelConfigurationUpdateWarpConnectorConfigurationErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zCloudflareTunnelConfigurationUpdateWarpConnectorConfigurationBody,
                path: zCloudflareTunnelConfigurationUpdateWarpConnectorConfigurationPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zCloudflareTunnelConfigurationUpdateWarpConnectorConfigurationResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-User-Service-Key', type: 'apiKey' }
            ],
            url: '/accounts/{account_id}/warp_connector/{tunnel_id}/configurations',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
}
