/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams, type RequestResult } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { CustomPagesErrorPageType, CustomPagesForAnAccountCreatePreviewTokenErrors, CustomPagesForAnAccountCreatePreviewTokenResponses, CustomPagesForAnAccountGetACustomPageErrors, CustomPagesForAnAccountGetACustomPageResponses, CustomPagesForAnAccountListCustomPagesErrors, CustomPagesForAnAccountListCustomPagesResponses, CustomPagesForAnAccountUpdateACustomPageErrors, CustomPagesForAnAccountUpdateACustomPageResponses, CustomPagesIdentifier, CustomPagesPreviewRequest, CustomPagesState, CustomPagesUrl } from '../types.gen';
import { zCustomPagesForAnAccountCreatePreviewTokenBody, zCustomPagesForAnAccountCreatePreviewTokenPath, zCustomPagesForAnAccountCreatePreviewTokenResponse, zCustomPagesForAnAccountGetACustomPagePath, zCustomPagesForAnAccountGetACustomPageResponse, zCustomPagesForAnAccountListCustomPagesPath, zCustomPagesForAnAccountListCustomPagesResponse, zCustomPagesForAnAccountUpdateACustomPageBody, zCustomPagesForAnAccountUpdateACustomPagePath, zCustomPagesForAnAccountUpdateACustomPageResponse } from '../zod.gen';

export class CustomPagesForAnAccountService {
    /**
     * List custom pages
     *
     * Fetches all the custom pages at the account level.
     */
    public static customPagesForAnAccountListCustomPages<ThrowOnError extends boolean = true>(parameters: {
        account_identifier: CustomPagesIdentifier;
    }, options?: Options<never, ThrowOnError>): RequestResult<CustomPagesForAnAccountListCustomPagesResponses, CustomPagesForAnAccountListCustomPagesErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'account_identifier' }] }]);
        return (options?.client ?? client).get<CustomPagesForAnAccountListCustomPagesResponses, CustomPagesForAnAccountListCustomPagesErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zCustomPagesForAnAccountListCustomPagesPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zCustomPagesForAnAccountListCustomPagesResponse.parseAsync(data),
            security: [{ name: 'X-Auth-Email', type: 'apiKey' }, { name: 'X-Auth-Key', type: 'apiKey' }],
            url: '/accounts/{account_identifier}/custom_pages',
            ...options,
            ...params
        });
    }
    
    /**
     * Create a preview token
     *
     * Creates a signed JWT token used to preview custom pages before they are published.
     */
    public static customPagesForAnAccountCreatePreviewToken<ThrowOnError extends boolean = true>(parameters: {
        account_identifier: CustomPagesIdentifier;
        customPagesPreviewRequest: CustomPagesPreviewRequest;
    }, options?: Options<never, ThrowOnError>): RequestResult<CustomPagesForAnAccountCreatePreviewTokenResponses, CustomPagesForAnAccountCreatePreviewTokenErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'account_identifier' }, { key: 'customPagesPreviewRequest', map: 'body' }] }]);
        return (options?.client ?? client).post<CustomPagesForAnAccountCreatePreviewTokenResponses, CustomPagesForAnAccountCreatePreviewTokenErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zCustomPagesForAnAccountCreatePreviewTokenBody,
                path: zCustomPagesForAnAccountCreatePreviewTokenPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zCustomPagesForAnAccountCreatePreviewTokenResponse.parseAsync(data),
            security: [{ name: 'X-Auth-Email', type: 'apiKey' }, { name: 'X-Auth-Key', type: 'apiKey' }],
            url: '/accounts/{account_identifier}/custom_pages/preview_tokens',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Get a custom page
     *
     * Fetches the details of a custom page.
     */
    public static customPagesForAnAccountGetACustomPage<ThrowOnError extends boolean = true>(parameters: {
        identifier: CustomPagesErrorPageType;
        account_identifier: CustomPagesIdentifier;
    }, options?: Options<never, ThrowOnError>): RequestResult<CustomPagesForAnAccountGetACustomPageResponses, CustomPagesForAnAccountGetACustomPageErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'identifier' }, { in: 'path', key: 'account_identifier' }] }]);
        return (options?.client ?? client).get<CustomPagesForAnAccountGetACustomPageResponses, CustomPagesForAnAccountGetACustomPageErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zCustomPagesForAnAccountGetACustomPagePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zCustomPagesForAnAccountGetACustomPageResponse.parseAsync(data),
            security: [{ name: 'X-Auth-Email', type: 'apiKey' }, { name: 'X-Auth-Key', type: 'apiKey' }],
            url: '/accounts/{account_identifier}/custom_pages/{identifier}',
            ...options,
            ...params
        });
    }
    
    /**
     * Update a custom page
     *
     * Updates the configuration of an existing custom page.
     */
    public static customPagesForAnAccountUpdateACustomPage<ThrowOnError extends boolean = true>(parameters: {
        identifier: CustomPagesErrorPageType;
        account_identifier: CustomPagesIdentifier;
        state: CustomPagesState;
        url: CustomPagesUrl;
    }, options?: Options<never, ThrowOnError>): RequestResult<CustomPagesForAnAccountUpdateACustomPageResponses, CustomPagesForAnAccountUpdateACustomPageErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'identifier' },
                    { in: 'path', key: 'account_identifier' },
                    { in: 'body', key: 'state' },
                    { in: 'body', key: 'url' }
                ] }]);
        return (options?.client ?? client).put<CustomPagesForAnAccountUpdateACustomPageResponses, CustomPagesForAnAccountUpdateACustomPageErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zCustomPagesForAnAccountUpdateACustomPageBody,
                path: zCustomPagesForAnAccountUpdateACustomPagePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zCustomPagesForAnAccountUpdateACustomPageResponse.parseAsync(data),
            security: [{ name: 'X-Auth-Email', type: 'apiKey' }, { name: 'X-Auth-Key', type: 'apiKey' }],
            url: '/accounts/{account_identifier}/custom_pages/{identifier}',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
}
