/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { CreateDeploymentGroupResponses, DeleteDeploymentGroupResponses, GetDeploymentGroupResponses, ListDeploymentGroupsResponses, TeamsDevicesDeploymentGroupCreateRequest, TeamsDevicesDeploymentGroupUpdateRequest, UpdateDeploymentGroupResponses } from '../types.gen';
import { zCreateDeploymentGroupBody, zCreateDeploymentGroupPath, zCreateDeploymentGroupResponse, zDeleteDeploymentGroupPath, zDeleteDeploymentGroupResponse, zGetDeploymentGroupPath, zGetDeploymentGroupResponse, zListDeploymentGroupsPath, zListDeploymentGroupsQuery, zListDeploymentGroupsResponse, zUpdateDeploymentGroupBody, zUpdateDeploymentGroupPath, zUpdateDeploymentGroupResponse } from '../zod.gen';

export class DeploymentGroupsService {
    /**
     * List deployment groups
     *
     * Lists all deployment groups for an account. Use deployment groups to assign target WARP client versions to specific devices. This endpoint is in Beta.
     */
    public static listDeploymentGroups<ThrowOnError extends boolean = true>(parameters: {
        account_id: string;
        page?: number;
        per_page?: number;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'account_id' },
                    { in: 'query', key: 'page' },
                    { in: 'query', key: 'per_page' }
                ] }]);
        return (options?.client ?? client).get<ListDeploymentGroupsResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zListDeploymentGroupsPath,
                query: zListDeploymentGroupsQuery.optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zListDeploymentGroupsResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/accounts/{account_id}/devices/deployment-groups',
            ...options,
            ...params
        });
    }
    
    /**
     * Create deployment group
     *
     * Creates a new deployment group. Policy IDs must be unique across all deployment groups. This endpoint is in Beta.
     */
    public static createDeploymentGroup<ThrowOnError extends boolean = true>(parameters: {
        account_id: string;
        teamsDevicesDeploymentGroupCreateRequest: TeamsDevicesDeploymentGroupCreateRequest;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'account_id' }, { key: 'teamsDevicesDeploymentGroupCreateRequest', map: 'body' }] }]);
        return (options?.client ?? client).post<CreateDeploymentGroupResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zCreateDeploymentGroupBody,
                path: zCreateDeploymentGroupPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zCreateDeploymentGroupResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/accounts/{account_id}/devices/deployment-groups',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Delete deployment group
     *
     * Deletes a deployment group. Associated policies no longer apply and devices stop receiving version targets. This endpoint is in Beta.
     */
    public static deleteDeploymentGroup<ThrowOnError extends boolean = true>(parameters: {
        account_id: string;
        group_id: string;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'account_id' }, { in: 'path', key: 'group_id' }] }]);
        return (options?.client ?? client).delete<DeleteDeploymentGroupResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zDeleteDeploymentGroupPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zDeleteDeploymentGroupResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/accounts/{account_id}/devices/deployment-groups/{group_id}',
            ...options,
            ...params
        });
    }
    
    /**
     * Get deployment group
     *
     * Fetches a single deployment group by its ID. This endpoint is in Beta.
     */
    public static getDeploymentGroup<ThrowOnError extends boolean = true>(parameters: {
        account_id: string;
        group_id: string;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'account_id' }, { in: 'path', key: 'group_id' }] }]);
        return (options?.client ?? client).get<GetDeploymentGroupResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zGetDeploymentGroupPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zGetDeploymentGroupResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/accounts/{account_id}/devices/deployment-groups/{group_id}',
            ...options,
            ...params
        });
    }
    
    /**
     * Update deployment group
     *
     * Updates a deployment group. Returns 409 if any newly added policy IDs already belong to another deployment group. This endpoint is in Beta.
     */
    public static updateDeploymentGroup<ThrowOnError extends boolean = true>(parameters: {
        account_id: string;
        group_id: string;
        teamsDevicesDeploymentGroupUpdateRequest: TeamsDevicesDeploymentGroupUpdateRequest;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'account_id' },
                    { in: 'path', key: 'group_id' },
                    { key: 'teamsDevicesDeploymentGroupUpdateRequest', map: 'body' }
                ] }]);
        return (options?.client ?? client).patch<UpdateDeploymentGroupResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zUpdateDeploymentGroupBody,
                path: zUpdateDeploymentGroupPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zUpdateDeploymentGroupResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/accounts/{account_id}/devices/deployment-groups/{group_id}',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
}
