/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { DlsAccountRegionalHostnamesAccountCreateHostnameErrors, DlsAccountRegionalHostnamesAccountCreateHostnameResponses, DlsAccountRegionalHostnamesAccountDeleteHostnameErrors, DlsAccountRegionalHostnamesAccountDeleteHostnameResponses, DlsAccountRegionalHostnamesAccountFetchHostnameErrors, DlsAccountRegionalHostnamesAccountFetchHostnameResponses, DlsAccountRegionalHostnamesAccountListHostnamesErrors, DlsAccountRegionalHostnamesAccountListHostnamesResponses, DlsAccountRegionalHostnamesAccountListRegionsErrors, DlsAccountRegionalHostnamesAccountListRegionsResponses, DlsAccountRegionalHostnamesAccountPatchHostnameErrors, DlsAccountRegionalHostnamesAccountPatchHostnameResponses, DlsHostname, DlsIdentifier, DlsRegionKey, DlsRouting } from '../types.gen';
import { zDlsAccountRegionalHostnamesAccountCreateHostnameBody, zDlsAccountRegionalHostnamesAccountCreateHostnamePath, zDlsAccountRegionalHostnamesAccountCreateHostnameResponse, zDlsAccountRegionalHostnamesAccountDeleteHostnamePath, zDlsAccountRegionalHostnamesAccountDeleteHostnameResponse, zDlsAccountRegionalHostnamesAccountFetchHostnamePath, zDlsAccountRegionalHostnamesAccountFetchHostnameResponse, zDlsAccountRegionalHostnamesAccountListHostnamesPath, zDlsAccountRegionalHostnamesAccountListHostnamesResponse, zDlsAccountRegionalHostnamesAccountListRegionsPath, zDlsAccountRegionalHostnamesAccountListRegionsResponse, zDlsAccountRegionalHostnamesAccountPatchHostnameBody, zDlsAccountRegionalHostnamesAccountPatchHostnamePath, zDlsAccountRegionalHostnamesAccountPatchHostnameResponse } from '../zod.gen';

export class DlsRegionalServicesService {
    /**
     * List Regions
     *
     * List all Regional Services regions available for use by this account.
     */
    public static dlsAccountRegionalHostnamesAccountListRegions<ThrowOnError extends boolean = true>(parameters: {
        account_id: DlsIdentifier;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'account_id' }] }]);
        return (options?.client ?? client).get<DlsAccountRegionalHostnamesAccountListRegionsResponses, DlsAccountRegionalHostnamesAccountListRegionsErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zDlsAccountRegionalHostnamesAccountListRegionsPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zDlsAccountRegionalHostnamesAccountListRegionsResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/accounts/{account_id}/addressing/regional_hostnames/regions',
            ...options,
            ...params
        });
    }
    
    /**
     * List Regional Hostnames
     *
     * List all Regional Hostnames within a zone.
     */
    public static dlsAccountRegionalHostnamesAccountListHostnames<ThrowOnError extends boolean = true>(parameters: {
        zone_id: DlsIdentifier;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }] }]);
        return (options?.client ?? client).get<DlsAccountRegionalHostnamesAccountListHostnamesResponses, DlsAccountRegionalHostnamesAccountListHostnamesErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zDlsAccountRegionalHostnamesAccountListHostnamesPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zDlsAccountRegionalHostnamesAccountListHostnamesResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/zones/{zone_id}/addressing/regional_hostnames',
            ...options,
            ...params
        });
    }
    
    /**
     * Create Regional Hostname
     *
     * Create a new Regional Hostname entry. Cloudflare will only use data centers that are physically located within the chosen region to decrypt and service HTTPS traffic. Learn more about [Regional Services](https://developers.cloudflare.com/data-localization/regional-services/get-started/).
     */
    public static dlsAccountRegionalHostnamesAccountCreateHostname<ThrowOnError extends boolean = true>(parameters: {
        zone_id: DlsIdentifier;
        hostname: DlsHostname;
        region_key: DlsRegionKey;
        routing?: DlsRouting;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'zone_id' },
                    { in: 'body', key: 'hostname' },
                    { in: 'body', key: 'region_key' },
                    { in: 'body', key: 'routing' }
                ] }]);
        return (options?.client ?? client).post<DlsAccountRegionalHostnamesAccountCreateHostnameResponses, DlsAccountRegionalHostnamesAccountCreateHostnameErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zDlsAccountRegionalHostnamesAccountCreateHostnameBody.optional(),
                path: zDlsAccountRegionalHostnamesAccountCreateHostnamePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zDlsAccountRegionalHostnamesAccountCreateHostnameResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/zones/{zone_id}/addressing/regional_hostnames',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Delete Regional Hostname
     *
     * Delete the region configuration for a specific Regional Hostname.
     */
    public static dlsAccountRegionalHostnamesAccountDeleteHostname<ThrowOnError extends boolean = true>(parameters: {
        zone_id: DlsIdentifier;
        hostname: DlsHostname;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }, { in: 'path', key: 'hostname' }] }]);
        return (options?.client ?? client).delete<DlsAccountRegionalHostnamesAccountDeleteHostnameResponses, DlsAccountRegionalHostnamesAccountDeleteHostnameErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zDlsAccountRegionalHostnamesAccountDeleteHostnamePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zDlsAccountRegionalHostnamesAccountDeleteHostnameResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/zones/{zone_id}/addressing/regional_hostnames/{hostname}',
            ...options,
            ...params
        });
    }
    
    /**
     * Fetch Regional Hostname
     *
     * Fetch the configuration for a specific Regional Hostname, within a zone.
     */
    public static dlsAccountRegionalHostnamesAccountFetchHostname<ThrowOnError extends boolean = true>(parameters: {
        zone_id: DlsIdentifier;
        hostname: DlsHostname;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }, { in: 'path', key: 'hostname' }] }]);
        return (options?.client ?? client).get<DlsAccountRegionalHostnamesAccountFetchHostnameResponses, DlsAccountRegionalHostnamesAccountFetchHostnameErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zDlsAccountRegionalHostnamesAccountFetchHostnamePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zDlsAccountRegionalHostnamesAccountFetchHostnameResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/zones/{zone_id}/addressing/regional_hostnames/{hostname}',
            ...options,
            ...params
        });
    }
    
    /**
     * Update Regional Hostname
     *
     * Update the configuration for a specific Regional Hostname. Only the region_key of a hostname is mutable.
     */
    public static dlsAccountRegionalHostnamesAccountPatchHostname<ThrowOnError extends boolean = true>(parameters: {
        zone_id: DlsIdentifier;
        hostname: DlsHostname;
        region_key: DlsRegionKey;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'zone_id' },
                    { in: 'path', key: 'hostname' },
                    { in: 'body', key: 'region_key' }
                ] }]);
        return (options?.client ?? client).patch<DlsAccountRegionalHostnamesAccountPatchHostnameResponses, DlsAccountRegionalHostnamesAccountPatchHostnameErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zDlsAccountRegionalHostnamesAccountPatchHostnameBody.optional(),
                path: zDlsAccountRegionalHostnamesAccountPatchHostnamePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zDlsAccountRegionalHostnamesAccountPatchHostnameResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/zones/{zone_id}/addressing/regional_hostnames/{hostname}',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
}
