/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { DnssecDeleteDnssecRecordsErrors, DnssecDeleteDnssecRecordsResponses, DnssecDnssecDetailsErrors, DnssecDnssecDetailsResponses, DnssecDnssecMultiSigner, DnssecDnssecPresigned, DnssecDnssecUseNsec3, DnssecEditDnssecStatusErrors, DnssecEditDnssecStatusResponses, DnssecIdentifier, DnssecListDnssecZsksErrors, DnssecListDnssecZsksResponses } from '../types.gen';
import { zDnssecDeleteDnssecRecordsBody, zDnssecDeleteDnssecRecordsPath, zDnssecDeleteDnssecRecordsResponse, zDnssecDnssecDetailsPath, zDnssecDnssecDetailsResponse, zDnssecEditDnssecStatusBody, zDnssecEditDnssecStatusPath, zDnssecEditDnssecStatusResponse, zDnssecListDnssecZsksPath, zDnssecListDnssecZsksResponse } from '../zod.gen';

export class DnssecService {
    /**
     * Delete DNSSEC records
     *
     * Delete DNSSEC.
     */
    public static dnssecDeleteDnssecRecords<ThrowOnError extends boolean = true>(parameters: {
        zone_id: DnssecIdentifier;
        body: unknown;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }, { key: 'body', map: 'body' }] }]);
        return (options?.client ?? client).delete<DnssecDeleteDnssecRecordsResponses, DnssecDeleteDnssecRecordsErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zDnssecDeleteDnssecRecordsBody,
                path: zDnssecDeleteDnssecRecordsPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zDnssecDeleteDnssecRecordsResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/dnssec',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * DNSSEC Details
     *
     * Details about DNSSEC status and configuration.
     */
    public static dnssecDnssecDetails<ThrowOnError extends boolean = true>(parameters: {
        zone_id: DnssecIdentifier;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }] }]);
        return (options?.client ?? client).get<DnssecDnssecDetailsResponses, DnssecDnssecDetailsErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zDnssecDnssecDetailsPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zDnssecDnssecDetailsResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/dnssec',
            ...options,
            ...params
        });
    }
    
    /**
     * Edit DNSSEC Status
     *
     * Enable or disable DNSSEC.
     */
    public static dnssecEditDnssecStatus<ThrowOnError extends boolean = true>(parameters: {
        zone_id: DnssecIdentifier;
        dnssec_multi_signer?: DnssecDnssecMultiSigner;
        dnssec_presigned?: DnssecDnssecPresigned;
        dnssec_use_nsec3?: DnssecDnssecUseNsec3;
        status?: 'active' | 'disabled';
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'zone_id' },
                    { in: 'body', key: 'dnssec_multi_signer' },
                    { in: 'body', key: 'dnssec_presigned' },
                    { in: 'body', key: 'dnssec_use_nsec3' },
                    { in: 'body', key: 'status' }
                ] }]);
        return (options?.client ?? client).patch<DnssecEditDnssecStatusResponses, DnssecEditDnssecStatusErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zDnssecEditDnssecStatusBody,
                path: zDnssecEditDnssecStatusPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zDnssecEditDnssecStatusResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/dnssec',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * List DNSSEC ZSKs
     *
     * List the Zone Signing Keys (ZSKs) that DNSSEC uses for the zone.
     */
    public static dnssecListDnssecZsks<ThrowOnError extends boolean = true>(parameters: {
        zone_id: DnssecIdentifier;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }] }]);
        return (options?.client ?? client).get<DnssecListDnssecZsksResponses, DnssecListDnssecZsksErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zDnssecListDnssecZsksPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zDnssecListDnssecZsksResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/dnssec/zsk',
            ...options,
            ...params
        });
    }
}
