/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams, type RequestResult } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { GetEventGraphErrors, GetEventGraphResponses } from '../types.gen';
import { zGetEventGraphPath, zGetEventGraphQuery, zGetEventGraphResponse } from '../zod.gen';

export class EventsService {
    /**
     * Query graph neighborhood from R2 Data Catalog
     *
     * Expands the single-level relationship neighborhood of one or more seed nodes (event, indicator, or tag) from R2 Data Catalog. Seeds use compact id format (type:uuid), e.g. "event:550e8400-...". Multi-seed requests merge and deduplicate results server-side. Hydrates neighbor entities with summary data from Durable Objects. Supports filtering by relationship type and dataset scope.
     */
    public static getEventGraph<ThrowOnError extends boolean = true>(parameters: {
        account_id: string;
        seeds?: Array<string>;
        direction?: string;
        hydration?: string;
        limit?: number;
        max_nodes?: number;
        relationshipTypes?: Array<string>;
        datasetIds?: Array<string>;
        cursor?: string;
        expand?: Array<string>;
    }, options?: Options<never, ThrowOnError>): RequestResult<GetEventGraphResponses, GetEventGraphErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'account_id' },
                    { in: 'query', key: 'seeds' },
                    { in: 'query', key: 'direction' },
                    { in: 'query', key: 'hydration' },
                    { in: 'query', key: 'limit' },
                    { in: 'query', key: 'max_nodes' },
                    { in: 'query', key: 'relationshipTypes' },
                    { in: 'query', key: 'datasetIds' },
                    { in: 'query', key: 'cursor' },
                    { in: 'query', key: 'expand' }
                ] }]);
        return (options?.client ?? client).get<GetEventGraphResponses, GetEventGraphErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zGetEventGraphPath,
                query: zGetEventGraphQuery.optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zGetEventGraphResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/accounts/{account_id}/cloudforce-one/events/graph',
            ...options,
            ...params
        });
    }
}
