/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { PostIndicatorTypeCreateErrors, PostIndicatorTypeCreateResponses } from '../types.gen';
import { zPostIndicatorTypeCreateBody, zPostIndicatorTypeCreatePath, zPostIndicatorTypeCreateResponse } from '../zod.gen';

export class IndicatorsService {
    /**
     * Create a new indicator type
     *
     * Creates a new indicator type and initializes its dedicated Durable Object
     */
    public static postIndicatorTypeCreate<ThrowOnError extends boolean = true>(parameters: {
        account_id: string;
        dataset_id: string;
        description?: string;
        indicatorType: string;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'account_id' },
                    { in: 'path', key: 'dataset_id' },
                    { in: 'body', key: 'description' },
                    { in: 'body', key: 'indicatorType' }
                ] }]);
        return (options?.client ?? client).post<PostIndicatorTypeCreateResponses, PostIndicatorTypeCreateErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zPostIndicatorTypeCreateBody.optional(),
                path: zPostIndicatorTypeCreatePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zPostIndicatorTypeCreateResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/accounts/{account_id}/cloudforce-one/events/dataset/{dataset_id}/indicatorTypes/create',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
}
