/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { FirewallAccountIdentifier, FirewallConfiguration, FirewallNotes, FirewallRuleIdentifier, FirewallSchemasMode, FirewallSchemasRuleWritable, IpAccessRulesForAnAccountCreateAnIpAccessRuleErrors, IpAccessRulesForAnAccountCreateAnIpAccessRuleResponses, IpAccessRulesForAnAccountDeleteAnIpAccessRuleErrors, IpAccessRulesForAnAccountDeleteAnIpAccessRuleResponses, IpAccessRulesForAnAccountGetAnIpAccessRuleErrors, IpAccessRulesForAnAccountGetAnIpAccessRuleResponses, IpAccessRulesForAnAccountListIpAccessRulesErrors, IpAccessRulesForAnAccountListIpAccessRulesResponses, IpAccessRulesForAnAccountUpdateAnIpAccessRuleErrors, IpAccessRulesForAnAccountUpdateAnIpAccessRuleResponses } from '../types.gen';
import { zIpAccessRulesForAnAccountCreateAnIpAccessRuleBody, zIpAccessRulesForAnAccountCreateAnIpAccessRulePath, zIpAccessRulesForAnAccountCreateAnIpAccessRuleResponse, zIpAccessRulesForAnAccountDeleteAnIpAccessRuleBody, zIpAccessRulesForAnAccountDeleteAnIpAccessRulePath, zIpAccessRulesForAnAccountDeleteAnIpAccessRuleResponse, zIpAccessRulesForAnAccountGetAnIpAccessRulePath, zIpAccessRulesForAnAccountGetAnIpAccessRuleResponse, zIpAccessRulesForAnAccountListIpAccessRulesPath, zIpAccessRulesForAnAccountListIpAccessRulesQuery, zIpAccessRulesForAnAccountListIpAccessRulesResponse, zIpAccessRulesForAnAccountUpdateAnIpAccessRuleBody, zIpAccessRulesForAnAccountUpdateAnIpAccessRulePath, zIpAccessRulesForAnAccountUpdateAnIpAccessRuleResponse } from '../zod.gen';

export class IpAccessRulesForAnAccountService {
    /**
     * List IP Access rules
     *
     * Fetches IP Access rules of an account. These rules apply to all the zones in the account. You can filter the results using several optional parameters.
     */
    public static ipAccessRulesForAnAccountListIpAccessRules<ThrowOnError extends boolean = true>(parameters: {
        account_id: FirewallAccountIdentifier;
        mode?: FirewallSchemasMode;
        'configuration.target'?: 'ip' | 'ip_range' | 'asn' | 'country';
        'configuration.value'?: string;
        notes?: string;
        match?: 'any' | 'all';
        page?: number;
        per_page?: number;
        order?: 'configuration.target' | 'configuration.value' | 'mode';
        direction?: 'asc' | 'desc';
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'account_id' },
                    { in: 'query', key: 'mode' },
                    { in: 'query', key: 'configuration.target' },
                    { in: 'query', key: 'configuration.value' },
                    { in: 'query', key: 'notes' },
                    { in: 'query', key: 'match' },
                    { in: 'query', key: 'page' },
                    { in: 'query', key: 'per_page' },
                    { in: 'query', key: 'order' },
                    { in: 'query', key: 'direction' }
                ] }]);
        return (options?.client ?? client).get<IpAccessRulesForAnAccountListIpAccessRulesResponses, IpAccessRulesForAnAccountListIpAccessRulesErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zIpAccessRulesForAnAccountListIpAccessRulesPath,
                query: zIpAccessRulesForAnAccountListIpAccessRulesQuery.optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zIpAccessRulesForAnAccountListIpAccessRulesResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/accounts/{account_id}/firewall/access_rules/rules',
            ...options,
            ...params
        });
    }
    
    /**
     * Create an IP Access rule
     *
     * Creates a new IP Access rule for an account. The rule will apply to all zones in the account.
     *
     * Note: To create an IP Access rule that applies to a single zone, refer to the [IP Access rules for a zone](#ip-access-rules-for-a-zone) endpoints.
     */
    public static ipAccessRulesForAnAccountCreateAnIpAccessRule<ThrowOnError extends boolean = true>(parameters: {
        account_id: FirewallAccountIdentifier;
        configuration: FirewallConfiguration;
        mode: FirewallSchemasMode;
        notes?: FirewallNotes & unknown;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'account_id' },
                    { in: 'body', key: 'configuration' },
                    { in: 'body', key: 'mode' },
                    { in: 'body', key: 'notes' }
                ] }]);
        return (options?.client ?? client).post<IpAccessRulesForAnAccountCreateAnIpAccessRuleResponses, IpAccessRulesForAnAccountCreateAnIpAccessRuleErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zIpAccessRulesForAnAccountCreateAnIpAccessRuleBody,
                path: zIpAccessRulesForAnAccountCreateAnIpAccessRulePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zIpAccessRulesForAnAccountCreateAnIpAccessRuleResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/accounts/{account_id}/firewall/access_rules/rules',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Delete an IP Access rule
     *
     * Deletes an existing IP Access rule defined at the account level.
     *
     * Note: This operation will affect all zones in the account.
     */
    public static ipAccessRulesForAnAccountDeleteAnIpAccessRule<ThrowOnError extends boolean = true>(parameters: {
        rule_id: FirewallRuleIdentifier;
        account_id: FirewallAccountIdentifier;
        body: unknown;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'rule_id' },
                    { in: 'path', key: 'account_id' },
                    { key: 'body', map: 'body' }
                ] }]);
        return (options?.client ?? client).delete<IpAccessRulesForAnAccountDeleteAnIpAccessRuleResponses, IpAccessRulesForAnAccountDeleteAnIpAccessRuleErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zIpAccessRulesForAnAccountDeleteAnIpAccessRuleBody,
                path: zIpAccessRulesForAnAccountDeleteAnIpAccessRulePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zIpAccessRulesForAnAccountDeleteAnIpAccessRuleResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/accounts/{account_id}/firewall/access_rules/rules/{rule_id}',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Get an IP Access rule
     *
     * Fetches the details of an IP Access rule defined at the account level.
     */
    public static ipAccessRulesForAnAccountGetAnIpAccessRule<ThrowOnError extends boolean = true>(parameters: {
        rule_id: FirewallRuleIdentifier;
        account_id: FirewallAccountIdentifier;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'rule_id' }, { in: 'path', key: 'account_id' }] }]);
        return (options?.client ?? client).get<IpAccessRulesForAnAccountGetAnIpAccessRuleResponses, IpAccessRulesForAnAccountGetAnIpAccessRuleErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zIpAccessRulesForAnAccountGetAnIpAccessRulePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zIpAccessRulesForAnAccountGetAnIpAccessRuleResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/accounts/{account_id}/firewall/access_rules/rules/{rule_id}',
            ...options,
            ...params
        });
    }
    
    /**
     * Update an IP Access rule
     *
     * Updates an IP Access rule defined at the account level.
     *
     * Note: This operation will affect all zones in the account.
     */
    public static ipAccessRulesForAnAccountUpdateAnIpAccessRule<ThrowOnError extends boolean = true>(parameters: {
        rule_id: FirewallRuleIdentifier;
        account_id: FirewallAccountIdentifier;
        firewallSchemasRuleWritable: FirewallSchemasRuleWritable;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'rule_id' },
                    { in: 'path', key: 'account_id' },
                    { key: 'firewallSchemasRuleWritable', map: 'body' }
                ] }]);
        return (options?.client ?? client).patch<IpAccessRulesForAnAccountUpdateAnIpAccessRuleResponses, IpAccessRulesForAnAccountUpdateAnIpAccessRuleErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zIpAccessRulesForAnAccountUpdateAnIpAccessRuleBody,
                path: zIpAccessRulesForAnAccountUpdateAnIpAccessRulePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zIpAccessRulesForAnAccountUpdateAnIpAccessRuleResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/accounts/{account_id}/firewall/access_rules/rules/{rule_id}',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
}
