/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { MagicNetworkMonitoringVpcFlowsGenerateAuthenticationTokenErrors, MagicNetworkMonitoringVpcFlowsGenerateAuthenticationTokenResponses, MagicVisibilityMnmAccountIdentifier } from '../types.gen';
import { zMagicNetworkMonitoringVpcFlowsGenerateAuthenticationTokenPath, zMagicNetworkMonitoringVpcFlowsGenerateAuthenticationTokenResponse } from '../zod.gen';

export class MagicNetworkMonitoringVpcFlowLogsService {
    /**
     * Generate authentication token for VPC flow logs export.
     *
     * Generate authentication token for VPC flow logs export.
     */
    public static magicNetworkMonitoringVpcFlowsGenerateAuthenticationToken<ThrowOnError extends boolean = true>(parameters: {
        account_id: MagicVisibilityMnmAccountIdentifier;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'account_id' }] }]);
        return (options?.client ?? client).post<MagicNetworkMonitoringVpcFlowsGenerateAuthenticationTokenResponses, MagicNetworkMonitoringVpcFlowsGenerateAuthenticationTokenErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zMagicNetworkMonitoringVpcFlowsGenerateAuthenticationTokenPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zMagicNetworkMonitoringVpcFlowsGenerateAuthenticationTokenResponse.parseAsync(data),
            security: [{ name: 'X-Auth-Email', type: 'apiKey' }, { name: 'X-Auth-Key', type: 'apiKey' }],
            url: '/accounts/{account_id}/mnm/vpc-flows/token',
            ...options,
            ...params
        });
    }
}
