/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams, type RequestResult } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { IamAccountIdentifierWritable, IamOauthClientCreateRequest, IamOauthClientIdentifier, IamOauthClientUpdateRequest, OauthClientsCreateErrors, OauthClientsCreateResponses, OauthClientsDeleteErrors, OauthClientsDeleteResponses, OauthClientsDeleteRotatedSecretErrors, OauthClientsDeleteRotatedSecretResponses, OauthClientsGetErrors, OauthClientsGetResponses, OauthClientsListErrors, OauthClientsListResponses, OauthClientsRotateSecretErrors, OauthClientsRotateSecretResponses, OauthClientsUpdateErrors, OauthClientsUpdateResponses, OauthScopesListErrors, OauthScopesListResponses } from '../types.gen';
import { zOauthClientsCreateBody, zOauthClientsCreatePath, zOauthClientsCreateResponse, zOauthClientsDeletePath, zOauthClientsDeleteResponse, zOauthClientsDeleteRotatedSecretPath, zOauthClientsDeleteRotatedSecretResponse, zOauthClientsGetPath, zOauthClientsGetResponse, zOauthClientsListPath, zOauthClientsListResponse, zOauthClientsRotateSecretPath, zOauthClientsRotateSecretResponse, zOauthClientsUpdateBody, zOauthClientsUpdatePath, zOauthClientsUpdateResponse, zOauthScopesListResponse } from '../zod.gen';

export class OAuthClientsService {
    /**
     * List OAuth Clients
     *
     * List all OAuth clients for an account.
     */
    public static oauthClientsList<ThrowOnError extends boolean = true>(parameters: {
        account_id: IamAccountIdentifierWritable;
    }, options?: Options<never, ThrowOnError>): RequestResult<OauthClientsListResponses, OauthClientsListErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'account_id' }] }]);
        return (options?.client ?? client).get<OauthClientsListResponses, OauthClientsListErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zOauthClientsListPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zOauthClientsListResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/accounts/{account_id}/oauth_clients',
            ...options,
            ...params
        });
    }
    
    /**
     * Create OAuth Client
     *
     * Create a new OAuth client for an account.
     */
    public static oauthClientsCreate<ThrowOnError extends boolean = true>(parameters: {
        account_id: IamAccountIdentifierWritable;
        iamOauthClientCreateRequest: IamOauthClientCreateRequest;
    }, options?: Options<never, ThrowOnError>): RequestResult<OauthClientsCreateResponses, OauthClientsCreateErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'account_id' }, { key: 'iamOauthClientCreateRequest', map: 'body' }] }]);
        return (options?.client ?? client).post<OauthClientsCreateResponses, OauthClientsCreateErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zOauthClientsCreateBody,
                path: zOauthClientsCreatePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zOauthClientsCreateResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/accounts/{account_id}/oauth_clients',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Delete OAuth Client
     *
     * Delete an OAuth client.
     */
    public static oauthClientsDelete<ThrowOnError extends boolean = true>(parameters: {
        account_id: IamAccountIdentifierWritable;
        oauth_client_id: IamOauthClientIdentifier;
    }, options?: Options<never, ThrowOnError>): RequestResult<OauthClientsDeleteResponses, OauthClientsDeleteErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'account_id' }, { in: 'path', key: 'oauth_client_id' }] }]);
        return (options?.client ?? client).delete<OauthClientsDeleteResponses, OauthClientsDeleteErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zOauthClientsDeletePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zOauthClientsDeleteResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/accounts/{account_id}/oauth_clients/{oauth_client_id}',
            ...options,
            ...params
        });
    }
    
    /**
     * OAuth Client Details
     *
     * Get details of a specific OAuth client.
     */
    public static oauthClientsGet<ThrowOnError extends boolean = true>(parameters: {
        account_id: IamAccountIdentifierWritable;
        oauth_client_id: IamOauthClientIdentifier;
    }, options?: Options<never, ThrowOnError>): RequestResult<OauthClientsGetResponses, OauthClientsGetErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'account_id' }, { in: 'path', key: 'oauth_client_id' }] }]);
        return (options?.client ?? client).get<OauthClientsGetResponses, OauthClientsGetErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zOauthClientsGetPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zOauthClientsGetResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/accounts/{account_id}/oauth_clients/{oauth_client_id}',
            ...options,
            ...params
        });
    }
    
    /**
     * Update OAuth Client
     *
     * Update an existing OAuth client. Only include fields you want to update.
     */
    public static oauthClientsUpdate<ThrowOnError extends boolean = true>(parameters: {
        account_id: IamAccountIdentifierWritable;
        oauth_client_id: IamOauthClientIdentifier;
        iamOauthClientUpdateRequest: IamOauthClientUpdateRequest;
    }, options?: Options<never, ThrowOnError>): RequestResult<OauthClientsUpdateResponses, OauthClientsUpdateErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'account_id' },
                    { in: 'path', key: 'oauth_client_id' },
                    { key: 'iamOauthClientUpdateRequest', map: 'body' }
                ] }]);
        return (options?.client ?? client).patch<OauthClientsUpdateResponses, OauthClientsUpdateErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zOauthClientsUpdateBody,
                path: zOauthClientsUpdatePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zOauthClientsUpdateResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/accounts/{account_id}/oauth_clients/{oauth_client_id}',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Delete Rotated OAuth Client Secret
     *
     * Removes the old client secret after a rotation, keeping only the new one. Use this after you have updated your client configuration to use the new secret. The `has_rotated_secret` field on the client indicates whether there is an old secret to delete.
     */
    public static oauthClientsDeleteRotatedSecret<ThrowOnError extends boolean = true>(parameters: {
        account_id: IamAccountIdentifierWritable;
        oauth_client_id: IamOauthClientIdentifier;
    }, options?: Options<never, ThrowOnError>): RequestResult<OauthClientsDeleteRotatedSecretResponses, OauthClientsDeleteRotatedSecretErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'account_id' }, { in: 'path', key: 'oauth_client_id' }] }]);
        return (options?.client ?? client).delete<OauthClientsDeleteRotatedSecretResponses, OauthClientsDeleteRotatedSecretErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zOauthClientsDeleteRotatedSecretPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zOauthClientsDeleteRotatedSecretResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/accounts/{account_id}/oauth_clients/{oauth_client_id}/rotate_secret',
            ...options,
            ...params
        });
    }
    
    /**
     * Rotate OAuth Client Secret
     *
     * Creates a second client secret so you can update your client configuration before deleting the old one. The `has_rotated_secret` field on the client will be set to `true`.
     */
    public static oauthClientsRotateSecret<ThrowOnError extends boolean = true>(parameters: {
        account_id: IamAccountIdentifierWritable;
        oauth_client_id: IamOauthClientIdentifier;
    }, options?: Options<never, ThrowOnError>): RequestResult<OauthClientsRotateSecretResponses, OauthClientsRotateSecretErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'account_id' }, { in: 'path', key: 'oauth_client_id' }] }]);
        return (options?.client ?? client).post<OauthClientsRotateSecretResponses, OauthClientsRotateSecretErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zOauthClientsRotateSecretPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zOauthClientsRotateSecretResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/accounts/{account_id}/oauth_clients/{oauth_client_id}/rotate_secret',
            ...options,
            ...params
        });
    }
    
    /**
     * List OAuth Scopes
     *
     * List all available OAuth scopes. This endpoint requires authentication but has no authorization role requirements.
     */
    public static oauthScopesList<ThrowOnError extends boolean = true>(options?: Options<never, ThrowOnError>): RequestResult<OauthScopesListResponses, OauthScopesListErrors, ThrowOnError> {
        return (options?.client ?? client).get<OauthScopesListResponses, OauthScopesListErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: z.never().optional(),
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zOauthScopesListResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/oauth/scopes',
            ...options
        });
    }
}
