/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { CacheRulesIdentifier, CacheRulesOriginPostQuantumEncryptionValue, ZoneCacheSettingsChangeOriginPostQuantumEncryptionSettingErrors, ZoneCacheSettingsChangeOriginPostQuantumEncryptionSettingResponses, ZoneCacheSettingsGetOriginPostQuantumEncryptionSettingErrors, ZoneCacheSettingsGetOriginPostQuantumEncryptionSettingResponses } from '../types.gen';
import { zZoneCacheSettingsChangeOriginPostQuantumEncryptionSettingBody, zZoneCacheSettingsChangeOriginPostQuantumEncryptionSettingPath, zZoneCacheSettingsChangeOriginPostQuantumEncryptionSettingResponse, zZoneCacheSettingsGetOriginPostQuantumEncryptionSettingPath, zZoneCacheSettingsGetOriginPostQuantumEncryptionSettingResponse } from '../zod.gen';

export class OriginPostQuantumService {
    /**
     * Get Origin Post-Quantum Encryption setting
     *
     * Instructs Cloudflare to use Post-Quantum (PQ) key agreement algorithms when connecting to your origin. Preferred instructs Cloudflare to opportunistically send a Post-Quantum keyshare in the first message to the origin (for fastest connections when the origin supports and prefers PQ), supported means that PQ algorithms are advertised but only used when requested by the origin, and off means that PQ algorithms are not advertised.
     */
    public static zoneCacheSettingsGetOriginPostQuantumEncryptionSetting<ThrowOnError extends boolean = true>(parameters: {
        zone_id: CacheRulesIdentifier;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }] }]);
        return (options?.client ?? client).get<ZoneCacheSettingsGetOriginPostQuantumEncryptionSettingResponses, ZoneCacheSettingsGetOriginPostQuantumEncryptionSettingErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zZoneCacheSettingsGetOriginPostQuantumEncryptionSettingPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zZoneCacheSettingsGetOriginPostQuantumEncryptionSettingResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/cache/origin_post_quantum_encryption',
            ...options,
            ...params
        });
    }
    
    /**
     * Change Origin Post-Quantum Encryption setting
     *
     * Instructs Cloudflare to use Post-Quantum (PQ) key agreement algorithms when connecting to your origin. Preferred instructs Cloudflare to opportunistically send a Post-Quantum keyshare in the first message to the origin (for fastest connections when the origin supports and prefers PQ), supported means that PQ algorithms are advertised but only used when requested by the origin, and off means that PQ algorithms are not advertised.
     */
    public static zoneCacheSettingsChangeOriginPostQuantumEncryptionSetting<ThrowOnError extends boolean = true>(parameters: {
        zone_id: CacheRulesIdentifier;
        value: CacheRulesOriginPostQuantumEncryptionValue;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }, { in: 'body', key: 'value' }] }]);
        return (options?.client ?? client).put<ZoneCacheSettingsChangeOriginPostQuantumEncryptionSettingResponses, ZoneCacheSettingsChangeOriginPostQuantumEncryptionSettingErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zZoneCacheSettingsChangeOriginPostQuantumEncryptionSettingBody,
                path: zZoneCacheSettingsChangeOriginPostQuantumEncryptionSettingPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zZoneCacheSettingsChangeOriginPostQuantumEncryptionSettingResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/cache/origin_post_quantum_encryption',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
}
