/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { CacheRulesIdentifier, CacheRulesOriginCloudRegionRequest, OriginCloudRegionsBatchDeleteErrors, OriginCloudRegionsBatchDeleteResponses, OriginCloudRegionsBatchUpsertErrors, OriginCloudRegionsBatchUpsertResponses, OriginCloudRegionsCreateErrors, OriginCloudRegionsCreateResponses, OriginCloudRegionsDeleteErrors, OriginCloudRegionsDeleteResponses, OriginCloudRegionsGetErrors, OriginCloudRegionsGetResponses, OriginCloudRegionsListErrors, OriginCloudRegionsListResponses, OriginCloudRegionsSupportedRegionsErrors, OriginCloudRegionsSupportedRegionsResponses, OriginCloudRegionsUpsertErrors, OriginCloudRegionsUpsertResponses } from '../types.gen';
import { zOriginCloudRegionsBatchDeleteBody, zOriginCloudRegionsBatchDeletePath, zOriginCloudRegionsBatchDeleteResponse, zOriginCloudRegionsBatchUpsertBody, zOriginCloudRegionsBatchUpsertPath, zOriginCloudRegionsBatchUpsertResponse, zOriginCloudRegionsCreateBody, zOriginCloudRegionsCreatePath, zOriginCloudRegionsCreateResponse, zOriginCloudRegionsDeletePath, zOriginCloudRegionsDeleteResponse, zOriginCloudRegionsGetPath, zOriginCloudRegionsGetResponse, zOriginCloudRegionsListPath, zOriginCloudRegionsListResponse, zOriginCloudRegionsSupportedRegionsPath, zOriginCloudRegionsSupportedRegionsResponse, zOriginCloudRegionsUpsertBody, zOriginCloudRegionsUpsertPath, zOriginCloudRegionsUpsertResponse } from '../zod.gen';

export class OriginCloudRegionsService {
    /**
     * List origin cloud region mappings
     *
     * Returns all IP-to-cloud-region mappings configured for the zone. Each mapping tells Cloudflare which cloud vendor and region hosts the origin at that IP, enabling the edge to route via the nearest Tiered Cache upper-tier co-located with that cloud provider. Returns an empty array when no mappings exist.
     */
    public static originCloudRegionsList<ThrowOnError extends boolean = true>(parameters: {
        zone_id: CacheRulesIdentifier;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }] }]);
        return (options?.client ?? client).get<OriginCloudRegionsListResponses, OriginCloudRegionsListErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zOriginCloudRegionsListPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zOriginCloudRegionsListResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/cache/origin_cloud_regions',
            ...options,
            ...params
        });
    }
    
    /**
     * Create or update an origin cloud region mapping
     *
     * Adds or updates a single IP-to-cloud-region mapping for the zone. Unlike POST, this operation is idempotent — if a mapping for the IP already exists it is overwritten. Returns the complete updated list of all mappings for the zone. Returns 403 (code 1164) when the zone has reached the limit of 3,500 IP mappings.
     */
    public static originCloudRegionsUpsert<ThrowOnError extends boolean = true>(parameters: {
        zone_id: CacheRulesIdentifier;
        cacheRulesOriginCloudRegionRequest: CacheRulesOriginCloudRegionRequest;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }, { key: 'cacheRulesOriginCloudRegionRequest', map: 'body' }] }]);
        return (options?.client ?? client).patch<OriginCloudRegionsUpsertResponses, OriginCloudRegionsUpsertErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zOriginCloudRegionsUpsertBody,
                path: zOriginCloudRegionsUpsertPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zOriginCloudRegionsUpsertResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/cache/origin_cloud_regions',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Create an origin cloud region mapping
     *
     * Adds a single IP-to-cloud-region mapping for the zone. The IP must be a valid IPv4 or IPv6 address and is normalized to canonical form before storage (RFC 5952 for IPv6). Returns 400 (code 1145) if a mapping for that IP already exists — use PATCH to update an existing entry. The vendor and region are validated against the list from `GET /zones/{zone_id}/cache/origin_cloud_regions/supported_regions`.
     */
    public static originCloudRegionsCreate<ThrowOnError extends boolean = true>(parameters: {
        zone_id: CacheRulesIdentifier;
        cacheRulesOriginCloudRegionRequest: CacheRulesOriginCloudRegionRequest;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }, { key: 'cacheRulesOriginCloudRegionRequest', map: 'body' }] }]);
        return (options?.client ?? client).post<OriginCloudRegionsCreateResponses, OriginCloudRegionsCreateErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zOriginCloudRegionsCreateBody,
                path: zOriginCloudRegionsCreatePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zOriginCloudRegionsCreateResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/cache/origin_cloud_regions',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Batch delete origin cloud region mappings
     *
     * Removes up to 100 IP-to-cloud-region mappings in a single request. Each IP is validated independently — successfully deleted items are returned in the `succeeded` array and IPs that could not be found or are invalid are returned in the `failed` array.
     */
    public static originCloudRegionsBatchDelete<ThrowOnError extends boolean = true>(parameters: {
        zone_id: CacheRulesIdentifier;
        body: Array<string>;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }, { key: 'body', map: 'body' }] }]);
        return (options?.client ?? client).delete<OriginCloudRegionsBatchDeleteResponses, OriginCloudRegionsBatchDeleteErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zOriginCloudRegionsBatchDeleteBody,
                path: zOriginCloudRegionsBatchDeletePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zOriginCloudRegionsBatchDeleteResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/cache/origin_cloud_regions/batch',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Batch create or update origin cloud region mappings
     *
     * Adds or updates up to 100 IP-to-cloud-region mappings in a single request. Each item is validated independently — valid items are applied and invalid items are returned in the `failed` array. The vendor and region for every item are validated against the list from `GET /zones/{zone_id}/cache/origin_cloud_regions/supported_regions`.
     */
    public static originCloudRegionsBatchUpsert<ThrowOnError extends boolean = true>(parameters: {
        zone_id: CacheRulesIdentifier;
        body: Array<CacheRulesOriginCloudRegionRequest>;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }, { key: 'body', map: 'body' }] }]);
        return (options?.client ?? client).patch<OriginCloudRegionsBatchUpsertResponses, OriginCloudRegionsBatchUpsertErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zOriginCloudRegionsBatchUpsertBody,
                path: zOriginCloudRegionsBatchUpsertPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zOriginCloudRegionsBatchUpsertResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/cache/origin_cloud_regions/batch',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * List supported cloud vendors and regions
     *
     * Returns the cloud vendors and regions that are valid values for origin cloud region mappings. Each region includes the Tiered Cache upper-tier colocation codes that will be used for cache routing when a mapping targeting that region is active. Requires the zone to have Tiered Cache enabled.
     */
    public static originCloudRegionsSupportedRegions<ThrowOnError extends boolean = true>(parameters: {
        zone_id: CacheRulesIdentifier;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }] }]);
        return (options?.client ?? client).get<OriginCloudRegionsSupportedRegionsResponses, OriginCloudRegionsSupportedRegionsErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zOriginCloudRegionsSupportedRegionsPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zOriginCloudRegionsSupportedRegionsResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/cache/origin_cloud_regions/supported_regions',
            ...options,
            ...params
        });
    }
    
    /**
     * Delete an origin cloud region mapping
     *
     * Removes the cloud region mapping for a single origin IP address. The IP path parameter is normalized before lookup. Returns the deleted entry on success. Returns 404 (code 1163) if no mapping exists for the specified IP. When the last mapping for the zone is removed the underlying rule record is also deleted.
     */
    public static originCloudRegionsDelete<ThrowOnError extends boolean = true>(parameters: {
        zone_id: CacheRulesIdentifier;
        origin_ip: string;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }, { in: 'path', key: 'origin_ip' }] }]);
        return (options?.client ?? client).delete<OriginCloudRegionsDeleteResponses, OriginCloudRegionsDeleteErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zOriginCloudRegionsDeletePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zOriginCloudRegionsDeleteResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/cache/origin_cloud_regions/{origin_ip}',
            ...options,
            ...params
        });
    }
    
    /**
     * Get an origin cloud region mapping
     *
     * Returns the cloud region mapping for a single origin IP address. The IP path parameter is normalized before lookup (RFC 5952 for IPv6). Returns 404 (code 1142) if the zone has no mappings or if the specified IP has no mapping.
     */
    public static originCloudRegionsGet<ThrowOnError extends boolean = true>(parameters: {
        zone_id: CacheRulesIdentifier;
        origin_ip: string;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }, { in: 'path', key: 'origin_ip' }] }]);
        return (options?.client ?? client).get<OriginCloudRegionsGetResponses, OriginCloudRegionsGetErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zOriginCloudRegionsGetPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zOriginCloudRegionsGetResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/cache/origin_cloud_regions/{origin_ip}',
            ...options,
            ...params
        });
    }
}
