/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams, type RequestResult } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { CacheAutoOriginTlsKexPatch, CacheIdentifier, CacheRulesIdentifier, CacheRulesOriginTlsComplianceModesValue, SslDetectorAutoOriginTlsKexGetEnrollmentErrors, SslDetectorAutoOriginTlsKexGetEnrollmentResponses, SslDetectorAutoOriginTlsKexPatchEnrollmentErrors, SslDetectorAutoOriginTlsKexPatchEnrollmentResponses, ZoneCacheSettingsChangeOriginTlsComplianceModesSettingErrors, ZoneCacheSettingsChangeOriginTlsComplianceModesSettingResponses, ZoneCacheSettingsDeleteOriginTlsComplianceModesSettingErrors, ZoneCacheSettingsDeleteOriginTlsComplianceModesSettingResponses, ZoneCacheSettingsGetOriginTlsComplianceModesSettingErrors, ZoneCacheSettingsGetOriginTlsComplianceModesSettingResponses, ZoneCacheSettingsReplaceOriginTlsComplianceModesSettingErrors, ZoneCacheSettingsReplaceOriginTlsComplianceModesSettingResponses } from '../types.gen';
import { zSslDetectorAutoOriginTlsKexGetEnrollmentPath, zSslDetectorAutoOriginTlsKexGetEnrollmentResponse, zSslDetectorAutoOriginTlsKexPatchEnrollmentBody, zSslDetectorAutoOriginTlsKexPatchEnrollmentPath, zSslDetectorAutoOriginTlsKexPatchEnrollmentResponse, zZoneCacheSettingsChangeOriginTlsComplianceModesSettingBody, zZoneCacheSettingsChangeOriginTlsComplianceModesSettingPath, zZoneCacheSettingsChangeOriginTlsComplianceModesSettingResponse, zZoneCacheSettingsDeleteOriginTlsComplianceModesSettingPath, zZoneCacheSettingsDeleteOriginTlsComplianceModesSettingResponse, zZoneCacheSettingsGetOriginTlsComplianceModesSettingPath, zZoneCacheSettingsGetOriginTlsComplianceModesSettingResponse, zZoneCacheSettingsReplaceOriginTlsComplianceModesSettingBody, zZoneCacheSettingsReplaceOriginTlsComplianceModesSettingPath, zZoneCacheSettingsReplaceOriginTlsComplianceModesSettingResponse } from '../zod.gen';

export class OriginTlsService {
    /**
     * Get Auto-Origin TLS KEX enrollment status for the given zone
     *
     * When enabled, Cloudflare automatically selects the preferred TLS key-exchange algorithm to use when establishing the TLS connection to the zone's origin, picking from the algorithms permitted by the zone's `origin_tls_compliance_modes` setting. When disabled, the default key-exchange ordering is used.
     */
    public static sslDetectorAutoOriginTlsKexGetEnrollment<ThrowOnError extends boolean = true>(parameters: {
        zone_id: CacheIdentifier;
    }, options?: Options<never, ThrowOnError>): RequestResult<SslDetectorAutoOriginTlsKexGetEnrollmentResponses, SslDetectorAutoOriginTlsKexGetEnrollmentErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }] }]);
        return (options?.client ?? client).get<SslDetectorAutoOriginTlsKexGetEnrollmentResponses, SslDetectorAutoOriginTlsKexGetEnrollmentErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zSslDetectorAutoOriginTlsKexGetEnrollmentPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zSslDetectorAutoOriginTlsKexGetEnrollmentResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/settings/auto_origin_tls_kex',
            ...options,
            ...params
        });
    }
    
    /**
     * Patch Auto-Origin TLS KEX enrollment status for the given zone
     *
     * Enable or disable Auto-Origin TLS KEX selection for the zone by sending `{"enabled": true}` or `{"enabled": false}`. When enabled, Cloudflare runs a periodic scan of the zone's origins to determine the preferred key-exchange algorithm and writes that preference to the edge so it is sent first in the TLS ClientHello to the origin.
     */
    public static sslDetectorAutoOriginTlsKexPatchEnrollment<ThrowOnError extends boolean = true>(parameters: {
        zone_id: CacheIdentifier;
        cacheAutoOriginTlsKexPatch: CacheAutoOriginTlsKexPatch;
    }, options?: Options<never, ThrowOnError>): RequestResult<SslDetectorAutoOriginTlsKexPatchEnrollmentResponses, SslDetectorAutoOriginTlsKexPatchEnrollmentErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }, { key: 'cacheAutoOriginTlsKexPatch', map: 'body' }] }]);
        return (options?.client ?? client).patch<SslDetectorAutoOriginTlsKexPatchEnrollmentResponses, SslDetectorAutoOriginTlsKexPatchEnrollmentErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zSslDetectorAutoOriginTlsKexPatchEnrollmentBody,
                path: zSslDetectorAutoOriginTlsKexPatchEnrollmentPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zSslDetectorAutoOriginTlsKexPatchEnrollmentResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/settings/auto_origin_tls_kex',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Delete Origin TLS Compliance Modes setting
     *
     * Delete the Origin TLS Compliance Modes setting for the zone, removing any configured compliance constraint. After deletion, Cloudflare's default behavior applies (no compliance filtering of the key-exchange algorithm list sent to the origin).
     */
    public static zoneCacheSettingsDeleteOriginTlsComplianceModesSetting<ThrowOnError extends boolean = true>(parameters: {
        zone_id: CacheRulesIdentifier;
    }, options?: Options<never, ThrowOnError>): RequestResult<ZoneCacheSettingsDeleteOriginTlsComplianceModesSettingResponses, ZoneCacheSettingsDeleteOriginTlsComplianceModesSettingErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }] }]);
        return (options?.client ?? client).delete<ZoneCacheSettingsDeleteOriginTlsComplianceModesSettingResponses, ZoneCacheSettingsDeleteOriginTlsComplianceModesSettingErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zZoneCacheSettingsDeleteOriginTlsComplianceModesSettingPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zZoneCacheSettingsDeleteOriginTlsComplianceModesSettingResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/settings/origin_tls_compliance_modes',
            ...options,
            ...params
        });
    }
    
    /**
     * Get Origin TLS Compliance Modes setting
     *
     * Origin TLS Compliance Modes constrains the set of TLS key-exchange algorithms Cloudflare may use when establishing the TLS connection to the zone's origin. The value is a list of named compliance modes (currently `fips` and `pqh`). Multiple modes are combined as the intersection of their permitted algorithm lists. An empty list (or no rule configured) means no compliance constraint is applied.
     */
    public static zoneCacheSettingsGetOriginTlsComplianceModesSetting<ThrowOnError extends boolean = true>(parameters: {
        zone_id: CacheRulesIdentifier;
    }, options?: Options<never, ThrowOnError>): RequestResult<ZoneCacheSettingsGetOriginTlsComplianceModesSettingResponses, ZoneCacheSettingsGetOriginTlsComplianceModesSettingErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }] }]);
        return (options?.client ?? client).get<ZoneCacheSettingsGetOriginTlsComplianceModesSettingResponses, ZoneCacheSettingsGetOriginTlsComplianceModesSettingErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zZoneCacheSettingsGetOriginTlsComplianceModesSettingPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zZoneCacheSettingsGetOriginTlsComplianceModesSettingResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/settings/origin_tls_compliance_modes',
            ...options,
            ...params
        });
    }
    
    /**
     * Change Origin TLS Compliance Modes setting
     *
     * Update the set of TLS compliance modes for the zone. PATCH performs a full replace of the modes list, not a merge — the request body is treated as the complete new list, and any modes not present in it are removed. (To remove a single mode from an existing configuration, send the updated list without it.) The request body must be of the form `{"value": ["fips", "pqh"]}`. Currently supported modes are `fips` and `pqh`; an empty list clears the constraint. Future modes (e.g. `cnsa2`) may be added; clients should treat unknown values as opaque strings. Invalid mode values are rejected with a 4xx response.
     */
    public static zoneCacheSettingsChangeOriginTlsComplianceModesSetting<ThrowOnError extends boolean = true>(parameters: {
        zone_id: CacheRulesIdentifier;
        value: CacheRulesOriginTlsComplianceModesValue;
    }, options?: Options<never, ThrowOnError>): RequestResult<ZoneCacheSettingsChangeOriginTlsComplianceModesSettingResponses, ZoneCacheSettingsChangeOriginTlsComplianceModesSettingErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }, { in: 'body', key: 'value' }] }]);
        return (options?.client ?? client).patch<ZoneCacheSettingsChangeOriginTlsComplianceModesSettingResponses, ZoneCacheSettingsChangeOriginTlsComplianceModesSettingErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zZoneCacheSettingsChangeOriginTlsComplianceModesSettingBody,
                path: zZoneCacheSettingsChangeOriginTlsComplianceModesSettingPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zZoneCacheSettingsChangeOriginTlsComplianceModesSettingResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/settings/origin_tls_compliance_modes',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Replace Origin TLS Compliance Modes setting
     *
     * Replace the entire set of TLS compliance modes for the zone with the list provided in the request body. PUT performs a full replace, not a merge — any modes not present in the request body are removed. The request body must be of the form `{"value": ["fips", "pqh"]}`. Currently supported modes are `fips` and `pqh`; an empty list clears the constraint. Future modes (e.g. `cnsa2`) may be added; clients should treat unknown values as opaque strings. Invalid mode values are rejected with a 4xx response.
     */
    public static zoneCacheSettingsReplaceOriginTlsComplianceModesSetting<ThrowOnError extends boolean = true>(parameters: {
        zone_id: CacheRulesIdentifier;
        value: CacheRulesOriginTlsComplianceModesValue;
    }, options?: Options<never, ThrowOnError>): RequestResult<ZoneCacheSettingsReplaceOriginTlsComplianceModesSettingResponses, ZoneCacheSettingsReplaceOriginTlsComplianceModesSettingErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }, { in: 'body', key: 'value' }] }]);
        return (options?.client ?? client).put<ZoneCacheSettingsReplaceOriginTlsComplianceModesSettingResponses, ZoneCacheSettingsReplaceOriginTlsComplianceModesSettingErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zZoneCacheSettingsReplaceOriginTlsComplianceModesSettingBody,
                path: zZoneCacheSettingsReplaceOriginTlsComplianceModesSettingPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zZoneCacheSettingsReplaceOriginTlsComplianceModesSettingResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/settings/origin_tls_compliance_modes',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
}
