/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams, type RequestResult } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { PagesAssetsCheckMissingErrors, PagesAssetsCheckMissingResponses, PagesAssetsUploadErrors, PagesAssetsUploadResponses, PagesAssetsUpsertHashesErrors, PagesAssetsUpsertHashesResponses, PagesPagesAssetsCheckMissingRequest, PagesPagesAssetsUploadRequest, PagesPagesAssetsUpsertHashesRequest } from '../types.gen';
import { zPagesAssetsCheckMissingBody, zPagesAssetsCheckMissingResponse, zPagesAssetsUploadBody, zPagesAssetsUploadResponse, zPagesAssetsUpsertHashesBody, zPagesAssetsUpsertHashesResponse } from '../zod.gen';

export class PagesAssetsService {
    /**
     * Check missing assets
     *
     * Check which of the provided file hashes are missing from the Pages
     * asset store. Returns a list of missing hashes that need to be uploaded.
     * Used as part of the Pages Direct Upload workflow.
     *
     * Authenticate with the JWT obtained from the upload-token endpoint:
     * GET /accounts/{account_id}/pages/projects/{project_name}/upload-token
     *
     */
    public static pagesAssetsCheckMissing<ThrowOnError extends boolean = true>(parameters: {
        pagesPagesAssetsCheckMissingRequest: PagesPagesAssetsCheckMissingRequest;
    }, options?: Options<never, ThrowOnError>): RequestResult<PagesAssetsCheckMissingResponses, PagesAssetsCheckMissingErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [{ key: 'pagesPagesAssetsCheckMissingRequest', map: 'body' }] }]);
        return (options?.client ?? client).post<PagesAssetsCheckMissingResponses, PagesAssetsCheckMissingErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zPagesAssetsCheckMissingBody,
                path: z.never().optional(),
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zPagesAssetsCheckMissingResponse.parseAsync(data),
            url: '/pages/assets/check-missing',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Upload asset
     *
     * Upload one or more files to the Pages asset store. Each file is
     * identified by its content hash and is uploaded using the same JSON shape
     * as the Cloudflare KV bulk write API. Used as part of the Pages Direct
     * Upload workflow.
     *
     * Authenticate with the JWT obtained from the upload-token endpoint:
     * GET /accounts/{account_id}/pages/projects/{project_name}/upload-token
     *
     */
    public static pagesAssetsUpload<ThrowOnError extends boolean = true>(parameters: {
        pagesPagesAssetsUploadRequest: PagesPagesAssetsUploadRequest;
    }, options?: Options<never, ThrowOnError>): RequestResult<PagesAssetsUploadResponses, PagesAssetsUploadErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [{ key: 'pagesPagesAssetsUploadRequest', map: 'body' }] }]);
        return (options?.client ?? client).post<PagesAssetsUploadResponses, PagesAssetsUploadErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zPagesAssetsUploadBody,
                path: z.never().optional(),
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zPagesAssetsUploadResponse.parseAsync(data),
            url: '/pages/assets/upload',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Upsert asset hashes
     *
     * Register the provided file hashes as recently uploaded to the Pages
     * asset store. Used as part of the Pages Direct Upload workflow so future
     * deployments can avoid re-uploading files that are already present.
     *
     * Authenticate with the JWT obtained from the upload-token endpoint:
     * GET /accounts/{account_id}/pages/projects/{project_name}/upload-token
     *
     */
    public static pagesAssetsUpsertHashes<ThrowOnError extends boolean = true>(parameters: {
        pagesPagesAssetsUpsertHashesRequest: PagesPagesAssetsUpsertHashesRequest;
    }, options?: Options<never, ThrowOnError>): RequestResult<PagesAssetsUpsertHashesResponses, PagesAssetsUpsertHashesErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [{ key: 'pagesPagesAssetsUpsertHashesRequest', map: 'body' }] }]);
        return (options?.client ?? client).post<PagesAssetsUpsertHashesResponses, PagesAssetsUpsertHashesErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zPagesAssetsUpsertHashesBody,
                path: z.never().optional(),
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zPagesAssetsUpsertHashesResponse.parseAsync(data),
            url: '/pages/assets/upsert-hashes',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
}
