/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { DeletePublicDeleteSuppressionRoutingErrors, DeletePublicDeleteSuppressionRoutingResponses, DeletePublicDeleteSuppressionSendingErrors, DeletePublicDeleteSuppressionSendingResponses, DeletePublicDeleteSuppressionZoneRoutingErrors, DeletePublicDeleteSuppressionZoneRoutingResponses, DeletePublicDeleteSuppressionZoneSendingErrors, DeletePublicDeleteSuppressionZoneSendingResponses, GetPublicFeedbackStatusResponses, GetPublicGetSuppressionRoutingErrors, GetPublicGetSuppressionRoutingResponses, GetPublicGetSuppressionSendingErrors, GetPublicGetSuppressionSendingResponses, GetPublicGetSuppressionZoneRoutingErrors, GetPublicGetSuppressionZoneRoutingResponses, GetPublicGetSuppressionZoneSendingErrors, GetPublicGetSuppressionZoneSendingResponses, GetPublicListSuppressionRoutingErrors, GetPublicListSuppressionRoutingResponses, GetPublicListSuppressionSendingErrors, GetPublicListSuppressionSendingResponses, GetPublicListSuppressionZoneRoutingErrors, GetPublicListSuppressionZoneRoutingResponses, GetPublicListSuppressionZoneSendingErrors, GetPublicListSuppressionZoneSendingResponses, PostPublicNewSuppressionRoutingErrors, PostPublicNewSuppressionRoutingResponses, PostPublicNewSuppressionSendingErrors, PostPublicNewSuppressionSendingResponses, PostPublicNewSuppressionZoneRoutingErrors, PostPublicNewSuppressionZoneRoutingResponses, PostPublicNewSuppressionZoneSendingErrors, PostPublicNewSuppressionZoneSendingResponses } from '../types.gen';
import { zDeletePublicDeleteSuppressionRoutingPath, zDeletePublicDeleteSuppressionRoutingResponse, zDeletePublicDeleteSuppressionSendingPath, zDeletePublicDeleteSuppressionSendingResponse, zDeletePublicDeleteSuppressionZoneRoutingPath, zDeletePublicDeleteSuppressionZoneRoutingResponse, zDeletePublicDeleteSuppressionZoneSendingPath, zDeletePublicDeleteSuppressionZoneSendingResponse, zGetPublicFeedbackStatusPath, zGetPublicFeedbackStatusQuery, zGetPublicFeedbackStatusResponse, zGetPublicGetSuppressionRoutingPath, zGetPublicGetSuppressionRoutingResponse, zGetPublicGetSuppressionSendingPath, zGetPublicGetSuppressionSendingResponse, zGetPublicGetSuppressionZoneRoutingPath, zGetPublicGetSuppressionZoneRoutingResponse, zGetPublicGetSuppressionZoneSendingPath, zGetPublicGetSuppressionZoneSendingResponse, zGetPublicListSuppressionRoutingPath, zGetPublicListSuppressionRoutingQuery, zGetPublicListSuppressionRoutingResponse, zGetPublicListSuppressionSendingPath, zGetPublicListSuppressionSendingQuery, zGetPublicListSuppressionSendingResponse, zGetPublicListSuppressionZoneRoutingPath, zGetPublicListSuppressionZoneRoutingQuery, zGetPublicListSuppressionZoneRoutingResponse, zGetPublicListSuppressionZoneSendingPath, zGetPublicListSuppressionZoneSendingQuery, zGetPublicListSuppressionZoneSendingResponse, zPostPublicNewSuppressionRoutingBody, zPostPublicNewSuppressionRoutingPath, zPostPublicNewSuppressionRoutingResponse, zPostPublicNewSuppressionSendingBody, zPostPublicNewSuppressionSendingPath, zPostPublicNewSuppressionSendingResponse, zPostPublicNewSuppressionZoneRoutingBody, zPostPublicNewSuppressionZoneRoutingPath, zPostPublicNewSuppressionZoneRoutingResponse, zPostPublicNewSuppressionZoneSendingBody, zPostPublicNewSuppressionZoneSendingPath, zPostPublicNewSuppressionZoneSendingResponse } from '../zod.gen';

export class PublicService {
    /**
     * List account email suppressions
     */
    public static getPublicListSuppressionRouting<ThrowOnError extends boolean = true>(parameters: {
        account_id: string;
        page?: number;
        per_page?: number;
        order?: 'email' | 'expires_at' | 'created_at';
        direction?: 'asc' | 'desc';
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'account_id' },
                    { in: 'query', key: 'page' },
                    { in: 'query', key: 'per_page' },
                    { in: 'query', key: 'order' },
                    { in: 'query', key: 'direction' }
                ] }]);
        return (options?.client ?? client).get<GetPublicListSuppressionRoutingResponses, GetPublicListSuppressionRoutingErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zGetPublicListSuppressionRoutingPath,
                query: zGetPublicListSuppressionRoutingQuery.optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zGetPublicListSuppressionRoutingResponse.parseAsync(data),
            url: '/accounts/{account_id}/email/routing/suppression',
            ...options,
            ...params
        });
    }
    
    /**
     * Create account email suppression
     */
    public static postPublicNewSuppressionRouting<ThrowOnError extends boolean = true>(parameters: {
        account_id: string;
        email: string;
        expires_at?: string | null;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'account_id' },
                    { in: 'body', key: 'email' },
                    { in: 'body', key: 'expires_at' }
                ] }]);
        return (options?.client ?? client).post<PostPublicNewSuppressionRoutingResponses, PostPublicNewSuppressionRoutingErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zPostPublicNewSuppressionRoutingBody.optional(),
                path: zPostPublicNewSuppressionRoutingPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zPostPublicNewSuppressionRoutingResponse.parseAsync(data),
            url: '/accounts/{account_id}/email/routing/suppression',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Delete account email suppression
     */
    public static deletePublicDeleteSuppressionRouting<ThrowOnError extends boolean = true>(parameters: {
        account_id: string;
        suppression_id: string;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'account_id' }, { in: 'path', key: 'suppression_id' }] }]);
        return (options?.client ?? client).delete<DeletePublicDeleteSuppressionRoutingResponses, DeletePublicDeleteSuppressionRoutingErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zDeletePublicDeleteSuppressionRoutingPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zDeletePublicDeleteSuppressionRoutingResponse.parseAsync(data),
            url: '/accounts/{account_id}/email/routing/suppression/{suppression_id}',
            ...options,
            ...params
        });
    }
    
    /**
     * Get account email suppression
     */
    public static getPublicGetSuppressionRouting<ThrowOnError extends boolean = true>(parameters: {
        account_id: string;
        suppression_id: string;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'account_id' }, { in: 'path', key: 'suppression_id' }] }]);
        return (options?.client ?? client).get<GetPublicGetSuppressionRoutingResponses, GetPublicGetSuppressionRoutingErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zGetPublicGetSuppressionRoutingPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zGetPublicGetSuppressionRoutingResponse.parseAsync(data),
            url: '/accounts/{account_id}/email/routing/suppression/{suppression_id}',
            ...options,
            ...params
        });
    }
    
    /**
     * Get feedback emails statistics
     */
    public static getPublicFeedbackStatus<ThrowOnError extends boolean = true>(parameters: {
        account_id: string;
        start_at?: string;
        end_at?: string;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'account_id' },
                    { in: 'query', key: 'start_at' },
                    { in: 'query', key: 'end_at' }
                ] }]);
        return (options?.client ?? client).get<GetPublicFeedbackStatusResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zGetPublicFeedbackStatusPath,
                query: zGetPublicFeedbackStatusQuery.optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zGetPublicFeedbackStatusResponse.parseAsync(data),
            url: '/accounts/{account_id}/email/sending/feedback',
            ...options,
            ...params
        });
    }
    
    /**
     * List account email suppressions
     */
    public static getPublicListSuppressionSending<ThrowOnError extends boolean = true>(parameters: {
        account_id: string;
        page?: number;
        per_page?: number;
        order?: 'email' | 'expires_at' | 'created_at';
        direction?: 'asc' | 'desc';
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'account_id' },
                    { in: 'query', key: 'page' },
                    { in: 'query', key: 'per_page' },
                    { in: 'query', key: 'order' },
                    { in: 'query', key: 'direction' }
                ] }]);
        return (options?.client ?? client).get<GetPublicListSuppressionSendingResponses, GetPublicListSuppressionSendingErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zGetPublicListSuppressionSendingPath,
                query: zGetPublicListSuppressionSendingQuery.optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zGetPublicListSuppressionSendingResponse.parseAsync(data),
            url: '/accounts/{account_id}/email/sending/suppression',
            ...options,
            ...params
        });
    }
    
    /**
     * Create account email suppression
     */
    public static postPublicNewSuppressionSending<ThrowOnError extends boolean = true>(parameters: {
        account_id: string;
        email: string;
        expires_at?: string | null;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'account_id' },
                    { in: 'body', key: 'email' },
                    { in: 'body', key: 'expires_at' }
                ] }]);
        return (options?.client ?? client).post<PostPublicNewSuppressionSendingResponses, PostPublicNewSuppressionSendingErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zPostPublicNewSuppressionSendingBody.optional(),
                path: zPostPublicNewSuppressionSendingPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zPostPublicNewSuppressionSendingResponse.parseAsync(data),
            url: '/accounts/{account_id}/email/sending/suppression',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Delete account email suppression
     */
    public static deletePublicDeleteSuppressionSending<ThrowOnError extends boolean = true>(parameters: {
        account_id: string;
        suppression_id: string;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'account_id' }, { in: 'path', key: 'suppression_id' }] }]);
        return (options?.client ?? client).delete<DeletePublicDeleteSuppressionSendingResponses, DeletePublicDeleteSuppressionSendingErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zDeletePublicDeleteSuppressionSendingPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zDeletePublicDeleteSuppressionSendingResponse.parseAsync(data),
            url: '/accounts/{account_id}/email/sending/suppression/{suppression_id}',
            ...options,
            ...params
        });
    }
    
    /**
     * Get account email suppression
     */
    public static getPublicGetSuppressionSending<ThrowOnError extends boolean = true>(parameters: {
        account_id: string;
        suppression_id: string;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'account_id' }, { in: 'path', key: 'suppression_id' }] }]);
        return (options?.client ?? client).get<GetPublicGetSuppressionSendingResponses, GetPublicGetSuppressionSendingErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zGetPublicGetSuppressionSendingPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zGetPublicGetSuppressionSendingResponse.parseAsync(data),
            url: '/accounts/{account_id}/email/sending/suppression/{suppression_id}',
            ...options,
            ...params
        });
    }
    
    /**
     * List zone email suppressions
     */
    public static getPublicListSuppressionZoneRouting<ThrowOnError extends boolean = true>(parameters: {
        zone_id: string;
        page?: number;
        per_page?: number;
        order?: 'email' | 'expires_at' | 'created_at';
        direction?: 'asc' | 'desc';
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'zone_id' },
                    { in: 'query', key: 'page' },
                    { in: 'query', key: 'per_page' },
                    { in: 'query', key: 'order' },
                    { in: 'query', key: 'direction' }
                ] }]);
        return (options?.client ?? client).get<GetPublicListSuppressionZoneRoutingResponses, GetPublicListSuppressionZoneRoutingErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zGetPublicListSuppressionZoneRoutingPath,
                query: zGetPublicListSuppressionZoneRoutingQuery.optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zGetPublicListSuppressionZoneRoutingResponse.parseAsync(data),
            url: '/zones/{zone_id}/email/routing/suppression',
            ...options,
            ...params
        });
    }
    
    /**
     * Create zone email suppression
     */
    public static postPublicNewSuppressionZoneRouting<ThrowOnError extends boolean = true>(parameters: {
        zone_id: string;
        email: string;
        expires_at?: string | null;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'zone_id' },
                    { in: 'body', key: 'email' },
                    { in: 'body', key: 'expires_at' }
                ] }]);
        return (options?.client ?? client).post<PostPublicNewSuppressionZoneRoutingResponses, PostPublicNewSuppressionZoneRoutingErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zPostPublicNewSuppressionZoneRoutingBody.optional(),
                path: zPostPublicNewSuppressionZoneRoutingPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zPostPublicNewSuppressionZoneRoutingResponse.parseAsync(data),
            url: '/zones/{zone_id}/email/routing/suppression',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Delete zone email suppression
     */
    public static deletePublicDeleteSuppressionZoneRouting<ThrowOnError extends boolean = true>(parameters: {
        zone_id: string;
        suppression_id: string;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }, { in: 'path', key: 'suppression_id' }] }]);
        return (options?.client ?? client).delete<DeletePublicDeleteSuppressionZoneRoutingResponses, DeletePublicDeleteSuppressionZoneRoutingErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zDeletePublicDeleteSuppressionZoneRoutingPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zDeletePublicDeleteSuppressionZoneRoutingResponse.parseAsync(data),
            url: '/zones/{zone_id}/email/routing/suppression/{suppression_id}',
            ...options,
            ...params
        });
    }
    
    /**
     * Get zone email suppression
     */
    public static getPublicGetSuppressionZoneRouting<ThrowOnError extends boolean = true>(parameters: {
        zone_id: string;
        suppression_id: string;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }, { in: 'path', key: 'suppression_id' }] }]);
        return (options?.client ?? client).get<GetPublicGetSuppressionZoneRoutingResponses, GetPublicGetSuppressionZoneRoutingErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zGetPublicGetSuppressionZoneRoutingPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zGetPublicGetSuppressionZoneRoutingResponse.parseAsync(data),
            url: '/zones/{zone_id}/email/routing/suppression/{suppression_id}',
            ...options,
            ...params
        });
    }
    
    /**
     * List zone email suppressions
     */
    public static getPublicListSuppressionZoneSending<ThrowOnError extends boolean = true>(parameters: {
        zone_id: string;
        page?: number;
        per_page?: number;
        order?: 'email' | 'expires_at' | 'created_at';
        direction?: 'asc' | 'desc';
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'zone_id' },
                    { in: 'query', key: 'page' },
                    { in: 'query', key: 'per_page' },
                    { in: 'query', key: 'order' },
                    { in: 'query', key: 'direction' }
                ] }]);
        return (options?.client ?? client).get<GetPublicListSuppressionZoneSendingResponses, GetPublicListSuppressionZoneSendingErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zGetPublicListSuppressionZoneSendingPath,
                query: zGetPublicListSuppressionZoneSendingQuery.optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zGetPublicListSuppressionZoneSendingResponse.parseAsync(data),
            url: '/zones/{zone_id}/email/sending/suppression',
            ...options,
            ...params
        });
    }
    
    /**
     * Create zone email suppression
     */
    public static postPublicNewSuppressionZoneSending<ThrowOnError extends boolean = true>(parameters: {
        zone_id: string;
        email: string;
        expires_at?: string | null;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'zone_id' },
                    { in: 'body', key: 'email' },
                    { in: 'body', key: 'expires_at' }
                ] }]);
        return (options?.client ?? client).post<PostPublicNewSuppressionZoneSendingResponses, PostPublicNewSuppressionZoneSendingErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zPostPublicNewSuppressionZoneSendingBody.optional(),
                path: zPostPublicNewSuppressionZoneSendingPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zPostPublicNewSuppressionZoneSendingResponse.parseAsync(data),
            url: '/zones/{zone_id}/email/sending/suppression',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Delete zone email suppression
     */
    public static deletePublicDeleteSuppressionZoneSending<ThrowOnError extends boolean = true>(parameters: {
        zone_id: string;
        suppression_id: string;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }, { in: 'path', key: 'suppression_id' }] }]);
        return (options?.client ?? client).delete<DeletePublicDeleteSuppressionZoneSendingResponses, DeletePublicDeleteSuppressionZoneSendingErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zDeletePublicDeleteSuppressionZoneSendingPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zDeletePublicDeleteSuppressionZoneSendingResponse.parseAsync(data),
            url: '/zones/{zone_id}/email/sending/suppression/{suppression_id}',
            ...options,
            ...params
        });
    }
    
    /**
     * Get zone email suppression
     */
    public static getPublicGetSuppressionZoneSending<ThrowOnError extends boolean = true>(parameters: {
        zone_id: string;
        suppression_id: string;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }, { in: 'path', key: 'suppression_id' }] }]);
        return (options?.client ?? client).get<GetPublicGetSuppressionZoneSendingResponses, GetPublicGetSuppressionZoneSendingErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zGetPublicGetSuppressionZoneSendingPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zGetPublicGetSuppressionZoneSendingResponse.parseAsync(data),
            url: '/zones/{zone_id}/email/sending/suppression/{suppression_id}',
            ...options,
            ...params
        });
    }
}
