/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { RadarGetEntitiesLocationByAlpha2Errors, RadarGetEntitiesLocationByAlpha2Responses, RadarGetEntitiesLocationsErrors, RadarGetEntitiesLocationsResponses } from '../types.gen';
import { zRadarGetEntitiesLocationByAlpha2Path, zRadarGetEntitiesLocationByAlpha2Query, zRadarGetEntitiesLocationByAlpha2Response, zRadarGetEntitiesLocationsQuery, zRadarGetEntitiesLocationsResponse } from '../zod.gen';

export class RadarLocationsService {
    /**
     * List locations
     *
     * Retrieves a list of locations.
     */
    public static radarGetEntitiesLocations<ThrowOnError extends boolean = true>(parameters?: {
        limit?: number;
        offset?: number;
        location?: string;
        region?: string;
        subregion?: string;
        continent?: 'AF' | 'AS' | 'EU' | 'NA' | 'OC' | 'SA';
        format?: 'JSON' | 'CSV';
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'query', key: 'limit' },
                    { in: 'query', key: 'offset' },
                    { in: 'query', key: 'location' },
                    { in: 'query', key: 'region' },
                    { in: 'query', key: 'subregion' },
                    { in: 'query', key: 'continent' },
                    { in: 'query', key: 'format' }
                ] }]);
        return (options?.client ?? client).get<RadarGetEntitiesLocationsResponses, RadarGetEntitiesLocationsErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: z.never().optional(),
                query: zRadarGetEntitiesLocationsQuery.optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zRadarGetEntitiesLocationsResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/radar/entities/locations',
            ...options,
            ...params
        });
    }
    
    /**
     * Get location details
     *
     * Retrieves the requested location information. (A confidence level below `5` indicates a low level of confidence in the traffic data - normally this happens because Cloudflare has a small amount of traffic from/to this location).
     */
    public static radarGetEntitiesLocationByAlpha2<ThrowOnError extends boolean = true>(parameters: {
        location: string;
        format?: 'JSON' | 'CSV';
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'location' }, { in: 'query', key: 'format' }] }]);
        return (options?.client ?? client).get<RadarGetEntitiesLocationByAlpha2Responses, RadarGetEntitiesLocationByAlpha2Errors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zRadarGetEntitiesLocationByAlpha2Path,
                query: zRadarGetEntitiesLocationByAlpha2Query.optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zRadarGetEntitiesLocationByAlpha2Response.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/radar/entities/locations/{location}',
            ...options,
            ...params
        });
    }
}
