/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { RadarGetSearchGlobalErrors, RadarGetSearchGlobalResponses } from '../types.gen';
import { zRadarGetSearchGlobalQuery, zRadarGetSearchGlobalResponse } from '../zod.gen';

export class RadarSearchService {
    /**
     * Search for locations, ASes, reports, and more
     *
     * Searches for locations, autonomous systems, reports, bots, certificate logs, certificate authorities, industries and verticals. Location names can be localized by sending an `Accept-Language` HTTP header with a BCP 47 language tag (e.g., `Accept-Language: pt-PT`). The full quality-value chain is supported (e.g., `pt-PT,pt;q=0.9,en;q=0.8`).
     */
    public static radarGetSearchGlobal<ThrowOnError extends boolean = true>(parameters: {
        limit?: number;
        limitPerGroup?: number;
        query: string;
        include?: Array<'ADM1S' | 'ASNS' | 'BOTS' | 'CERTIFICATE_AUTHORITIES' | 'CERTIFICATE_LOGS' | 'ORIGINS' | 'ORIGIN_REGIONS' | 'INDUSTRIES' | 'LOCATIONS' | 'NOTEBOOKS' | 'TLDS' | 'VERTICALS'>;
        exclude?: Array<'ADM1S' | 'ASNS' | 'BOTS' | 'CERTIFICATE_AUTHORITIES' | 'CERTIFICATE_LOGS' | 'ORIGINS' | 'ORIGIN_REGIONS' | 'INDUSTRIES' | 'LOCATIONS' | 'NOTEBOOKS' | 'TLDS' | 'VERTICALS'>;
        format?: 'JSON' | 'CSV';
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'query', key: 'limit' },
                    { in: 'query', key: 'limitPerGroup' },
                    { in: 'query', key: 'query' },
                    { in: 'query', key: 'include' },
                    { in: 'query', key: 'exclude' },
                    { in: 'query', key: 'format' }
                ] }]);
        return (options?.client ?? client).get<RadarGetSearchGlobalResponses, RadarGetSearchGlobalErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: z.never().optional(),
                query: zRadarGetSearchGlobalQuery
            }).parseAsync(data),
            responseValidator: async (data) => await zRadarGetSearchGlobalResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/radar/search/global',
            ...options,
            ...params
        });
    }
}
