/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { RadarGetGeolocationDetailsErrors, RadarGetGeolocationDetailsResponses, RadarGetGeolocationsErrors, RadarGetGeolocationsResponses } from '../types.gen';
import { zRadarGetGeolocationDetailsPath, zRadarGetGeolocationDetailsQuery, zRadarGetGeolocationDetailsResponse, zRadarGetGeolocationsQuery, zRadarGetGeolocationsResponse } from '../zod.gen';

export class RadarGeolocationsService {
    /**
     * List Geolocations
     *
     * Retrieves a list of geolocations. Geolocation names can be localized by sending an `Accept-Language` HTTP header with a BCP 47 language tag (e.g., `Accept-Language: pt-PT`). The full quality-value chain is supported (e.g., `pt-PT,pt;q=0.9,en;q=0.8`).
     */
    public static radarGetGeolocations<ThrowOnError extends boolean = true>(parameters?: {
        limit?: number;
        offset?: number;
        geoId?: string;
        location?: string;
        format?: 'JSON' | 'CSV';
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'query', key: 'limit' },
                    { in: 'query', key: 'offset' },
                    { in: 'query', key: 'geoId' },
                    { in: 'query', key: 'location' },
                    { in: 'query', key: 'format' }
                ] }]);
        return (options?.client ?? client).get<RadarGetGeolocationsResponses, RadarGetGeolocationsErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: z.never().optional(),
                query: zRadarGetGeolocationsQuery.optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zRadarGetGeolocationsResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/radar/geolocations',
            ...options,
            ...params
        });
    }
    
    /**
     * Get Geolocation details
     *
     * Retrieves the requested Geolocation information. Geolocation names can be localized by sending an `Accept-Language` HTTP header with a BCP 47 language tag (e.g., `Accept-Language: pt-PT`). The full quality-value chain is supported (e.g., `pt-PT,pt;q=0.9,en;q=0.8`).
     */
    public static radarGetGeolocationDetails<ThrowOnError extends boolean = true>(parameters: {
        geo_id: string;
        format?: 'JSON' | 'CSV';
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'geo_id' }, { in: 'query', key: 'format' }] }]);
        return (options?.client ?? client).get<RadarGetGeolocationDetailsResponses, RadarGetGeolocationDetailsErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zRadarGetGeolocationDetailsPath,
                query: zRadarGetGeolocationDetailsQuery.optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zRadarGetGeolocationDetailsResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/radar/geolocations/{geo_id}',
            ...options,
            ...params
        });
    }
}
