/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { GetActiveRecordingErrors, GetActiveRecordingResponses, GetAllRecordingsResponses, GetOneRecordingResponses, PauseResumeStopRecordingResponses, RealtimekitAccountIdentifier, RealtimekitAppId, RealtimekitStartRecording, RealtimekitStartTrackRecordingBody, StartRecordingResponses, StartTrackRecordingForAMeetingResponses } from '../types.gen';
import { zGetActiveRecordingPath, zGetActiveRecordingResponse, zGetAllRecordingsPath, zGetAllRecordingsQuery, zGetAllRecordingsResponse, zGetOneRecordingPath, zGetOneRecordingResponse, zPauseResumeStopRecordingBody, zPauseResumeStopRecordingPath, zPauseResumeStopRecordingResponse, zStartRecordingBody, zStartRecordingPath, zStartRecordingResponse, zStartTrackRecordingForAMeetingBody, zStartTrackRecordingForAMeetingPath } from '../zod.gen';

export class RecordingsService {
    /**
     * Fetch all recordings for an App
     *
     * Returns all recordings for an App. If the `meeting_id` parameter is passed, returns all recordings for the given meeting ID.
     */
    public static getAllRecordings<ThrowOnError extends boolean = true>(parameters: {
        account_id: RealtimekitAccountIdentifier;
        app_id: RealtimekitAppId;
        meeting_id?: string;
        page_no?: number;
        per_page?: number;
        expired?: boolean;
        search?: string;
        sort_by?: 'invokedTime';
        sort_order?: 'ASC' | 'DESC';
        start_time?: string;
        end_time?: string;
        status?: Array<'INVOKED' | 'RECORDING' | 'UPLOADING' | 'UPLOADED'>;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'account_id' },
                    { in: 'path', key: 'app_id' },
                    { in: 'query', key: 'meeting_id' },
                    { in: 'query', key: 'page_no' },
                    { in: 'query', key: 'per_page' },
                    { in: 'query', key: 'expired' },
                    { in: 'query', key: 'search' },
                    { in: 'query', key: 'sort_by' },
                    { in: 'query', key: 'sort_order' },
                    { in: 'query', key: 'start_time' },
                    { in: 'query', key: 'end_time' },
                    { in: 'query', key: 'status' }
                ] }]);
        return (options?.client ?? client).get<GetAllRecordingsResponses, unknown, ThrowOnError>({
            querySerializer: { parameters: { status: { array: { explode: false } } } },
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zGetAllRecordingsPath,
                query: zGetAllRecordingsQuery.optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zGetAllRecordingsResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/accounts/{account_id}/realtime/kit/{app_id}/recordings',
            ...options,
            ...params
        });
    }
    
    /**
     * Start recording a meeting
     *
     * Starts recording a meeting. The meeting can be started by an App admin directly, or a participant with permissions to start a recording, based on the type of authorization used.
     */
    public static startRecording<ThrowOnError extends boolean = true>(parameters: {
        account_id: RealtimekitAccountIdentifier;
        app_id: RealtimekitAppId;
        realtimekitStartRecording: RealtimekitStartRecording;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'account_id' },
                    { in: 'path', key: 'app_id' },
                    { key: 'realtimekitStartRecording', map: 'body' }
                ] }]);
        return (options?.client ?? client).post<StartRecordingResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zStartRecordingBody,
                path: zStartRecordingPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zStartRecordingResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/accounts/{account_id}/realtime/kit/{app_id}/recordings',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Fetch active recording
     *
     * Returns the active recording details for the given meeting ID.
     */
    public static getActiveRecording<ThrowOnError extends boolean = true>(parameters: {
        account_id: RealtimekitAccountIdentifier;
        app_id: RealtimekitAppId;
        meeting_id: string;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'account_id' },
                    { in: 'path', key: 'app_id' },
                    { in: 'path', key: 'meeting_id' }
                ] }]);
        return (options?.client ?? client).get<GetActiveRecordingResponses, GetActiveRecordingErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zGetActiveRecordingPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zGetActiveRecordingResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/accounts/{account_id}/realtime/kit/{app_id}/recordings/active-recording/{meeting_id}',
            ...options,
            ...params
        });
    }
    
    /**
     * Start recording audio and video tracks
     *
     * Starts a track recording in a meeting. Track recordings consist of "layers". Layers are used to map audio/video tracks in a meeting to output destinations. More information about track recordings is available in the [Track Recordings Guide Page](https://docs.realtime.cloudflare.com/guides/capabilities/recording/recording-overview).
     */
    public static startTrackRecordingForAMeeting<ThrowOnError extends boolean = true>(parameters: {
        account_id: RealtimekitAccountIdentifier;
        app_id: RealtimekitAppId;
        realtimekitStartTrackRecordingBody: RealtimekitStartTrackRecordingBody;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'account_id' },
                    { in: 'path', key: 'app_id' },
                    { key: 'realtimekitStartTrackRecordingBody', map: 'body' }
                ] }]);
        return (options?.client ?? client).post<StartTrackRecordingForAMeetingResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zStartTrackRecordingForAMeetingBody,
                path: zStartTrackRecordingForAMeetingPath,
                query: z.never().optional()
            }).parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/accounts/{account_id}/realtime/kit/{app_id}/recordings/track',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Fetch details of a recording
     *
     * Returns details of a recording for the given recording ID.
     */
    public static getOneRecording<ThrowOnError extends boolean = true>(parameters: {
        account_id: RealtimekitAccountIdentifier;
        app_id: RealtimekitAppId;
        recording_id: string;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'account_id' },
                    { in: 'path', key: 'app_id' },
                    { in: 'path', key: 'recording_id' }
                ] }]);
        return (options?.client ?? client).get<GetOneRecordingResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zGetOneRecordingPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zGetOneRecordingResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/accounts/{account_id}/realtime/kit/{app_id}/recordings/{recording_id}',
            ...options,
            ...params
        });
    }
    
    /**
     * Pause/Resume/Stop recording
     *
     * Pause/Resume/Stop a given recording ID.
     */
    public static pauseResumeStopRecording<ThrowOnError extends boolean = true>(parameters: {
        account_id: RealtimekitAccountIdentifier;
        app_id: string;
        recording_id: string;
        action: 'stop' | 'pause' | 'resume';
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'account_id' },
                    { in: 'path', key: 'app_id' },
                    { in: 'path', key: 'recording_id' },
                    { in: 'body', key: 'action' }
                ] }]);
        return (options?.client ?? client).put<PauseResumeStopRecordingResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zPauseResumeStopRecordingBody,
                path: zPauseResumeStopRecordingPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zPauseResumeStopRecordingResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/accounts/{account_id}/realtime/kit/{app_id}/recordings/{recording_id}',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
}
