/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams, type RequestResult } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { CcApplicationId, CcCreateApplicationRolloutRequest, CreateApplicationRolloutErrors, CreateApplicationRolloutResponses } from '../types.gen';
import { zCreateApplicationRolloutBody, zCreateApplicationRolloutPath, zCreateApplicationRolloutResponse } from '../zod.gen';

export class RolloutsService {
    /**
     * Create a new rollout for an application
     *
     * A rollout can be used to update the application's configuration across instances with minimal downtime.
     */
    public static createApplicationRollout<ThrowOnError extends boolean = true>(parameters: {
        account_id: string;
        application_id: CcApplicationId;
        ccCreateApplicationRolloutRequest: CcCreateApplicationRolloutRequest;
    }, options?: Options<never, ThrowOnError>): RequestResult<CreateApplicationRolloutResponses, CreateApplicationRolloutErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'account_id' },
                    { in: 'path', key: 'application_id' },
                    { key: 'ccCreateApplicationRolloutRequest', map: 'body' }
                ] }]);
        return (options?.client ?? client).post<CreateApplicationRolloutResponses, CreateApplicationRolloutErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zCreateApplicationRolloutBody,
                path: zCreateApplicationRolloutPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zCreateApplicationRolloutResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/accounts/{account_id}/containers/applications/{application_id}/rollouts',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
}
