/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { ApiShieldSchemaCreate, ApiShieldSchemaEdit, ApiShieldSchemasIdentifier, ApiShieldSchemasUuidWritable, SchemaValidationCreateSchemaErrors, SchemaValidationCreateSchemaResponses, SchemaValidationDeleteSchemaErrors, SchemaValidationDeleteSchemaResponses, SchemaValidationEditSchemaErrors, SchemaValidationEditSchemaResponses, SchemaValidationExtractOperationsFromSchemaErrors, SchemaValidationExtractOperationsFromSchemaResponses, SchemaValidationGetSchemaErrors, SchemaValidationGetSchemaResponses, SchemaValidationListSchemaHostsErrors, SchemaValidationListSchemaHostsResponses, SchemaValidationListSchemasPaginatedErrors, SchemaValidationListSchemasPaginatedResponses } from '../types.gen';
import { zSchemaValidationCreateSchemaBody, zSchemaValidationCreateSchemaPath, zSchemaValidationCreateSchemaResponse, zSchemaValidationDeleteSchemaPath, zSchemaValidationDeleteSchemaResponse, zSchemaValidationEditSchemaBody, zSchemaValidationEditSchemaPath, zSchemaValidationEditSchemaResponse, zSchemaValidationExtractOperationsFromSchemaPath, zSchemaValidationExtractOperationsFromSchemaQuery, zSchemaValidationExtractOperationsFromSchemaResponse, zSchemaValidationGetSchemaPath, zSchemaValidationGetSchemaQuery, zSchemaValidationGetSchemaResponse, zSchemaValidationListSchemaHostsPath, zSchemaValidationListSchemaHostsQuery, zSchemaValidationListSchemaHostsResponse, zSchemaValidationListSchemasPaginatedPath, zSchemaValidationListSchemasPaginatedQuery, zSchemaValidationListSchemasPaginatedResponse } from '../zod.gen';

export class SchemaValidationService {
    /**
     * List all uploaded schemas
     *
     * Lists all OpenAPI schemas uploaded to API Shield with pagination support.
     */
    public static schemaValidationListSchemasPaginated<ThrowOnError extends boolean = true>(parameters: {
        zone_id: ApiShieldSchemasIdentifier;
        page?: number;
        per_page?: number;
        omit_source?: boolean;
        validation_enabled?: boolean;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'zone_id' },
                    { in: 'query', key: 'page' },
                    { in: 'query', key: 'per_page' },
                    { in: 'query', key: 'omit_source' },
                    { in: 'query', key: 'validation_enabled' }
                ] }]);
        return (options?.client ?? client).get<SchemaValidationListSchemasPaginatedResponses, SchemaValidationListSchemasPaginatedErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zSchemaValidationListSchemasPaginatedPath,
                query: zSchemaValidationListSchemasPaginatedQuery.optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zSchemaValidationListSchemasPaginatedResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/schema_validation/schemas',
            ...options,
            ...params
        });
    }
    
    /**
     * Upload a schema
     *
     * Uploads a new OpenAPI schema for API Shield schema validation. The schema defines expected request/response formats for API endpoints.
     */
    public static schemaValidationCreateSchema<ThrowOnError extends boolean = true>(parameters: {
        zone_id: ApiShieldSchemasIdentifier;
        apiShieldSchemaCreate: ApiShieldSchemaCreate;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }, { key: 'apiShieldSchemaCreate', map: 'body' }] }]);
        return (options?.client ?? client).post<SchemaValidationCreateSchemaResponses, SchemaValidationCreateSchemaErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zSchemaValidationCreateSchemaBody,
                path: zSchemaValidationCreateSchemaPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zSchemaValidationCreateSchemaResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/schema_validation/schemas',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * List hosts covered by uploaded schemas
     *
     * Lists all unique hosts found in uploaded OpenAPI schemas for the zone.
     */
    public static schemaValidationListSchemaHosts<ThrowOnError extends boolean = true>(parameters: {
        zone_id: ApiShieldSchemasIdentifier;
        page?: number;
        per_page?: number;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'zone_id' },
                    { in: 'query', key: 'page' },
                    { in: 'query', key: 'per_page' }
                ] }]);
        return (options?.client ?? client).get<SchemaValidationListSchemaHostsResponses, SchemaValidationListSchemaHostsErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zSchemaValidationListSchemaHostsPath,
                query: zSchemaValidationListSchemaHostsQuery.optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zSchemaValidationListSchemaHostsResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/schema_validation/schemas/hosts',
            ...options,
            ...params
        });
    }
    
    /**
     * Delete a schema
     *
     * Permanently removes an uploaded OpenAPI schema from API Shield. Operations using this schema will lose their validation rules.
     */
    public static schemaValidationDeleteSchema<ThrowOnError extends boolean = true>(parameters: {
        zone_id: ApiShieldSchemasIdentifier;
        schema_id: ApiShieldSchemasUuidWritable & string;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }, { in: 'path', key: 'schema_id' }] }]);
        return (options?.client ?? client).delete<SchemaValidationDeleteSchemaResponses, SchemaValidationDeleteSchemaErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zSchemaValidationDeleteSchemaPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zSchemaValidationDeleteSchemaResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/schema_validation/schemas/{schema_id}',
            ...options,
            ...params
        });
    }
    
    /**
     * Get details of a schema
     *
     * Gets the contents and metadata of a specific OpenAPI schema uploaded to API Shield.
     */
    public static schemaValidationGetSchema<ThrowOnError extends boolean = true>(parameters: {
        zone_id: ApiShieldSchemasIdentifier;
        schema_id: ApiShieldSchemasUuidWritable & string;
        omit_source?: boolean;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'zone_id' },
                    { in: 'path', key: 'schema_id' },
                    { in: 'query', key: 'omit_source' }
                ] }]);
        return (options?.client ?? client).get<SchemaValidationGetSchemaResponses, SchemaValidationGetSchemaErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zSchemaValidationGetSchemaPath,
                query: zSchemaValidationGetSchemaQuery.optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zSchemaValidationGetSchemaResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/schema_validation/schemas/{schema_id}',
            ...options,
            ...params
        });
    }
    
    /**
     * Edit details of a schema to enable validation
     *
     * Modifies an existing OpenAPI schema in API Shield, updating the validation rules for associated API operations.
     */
    public static schemaValidationEditSchema<ThrowOnError extends boolean = true>(parameters: {
        zone_id: ApiShieldSchemasIdentifier;
        schema_id: ApiShieldSchemasUuidWritable & string;
        apiShieldSchemaEdit: ApiShieldSchemaEdit;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'zone_id' },
                    { in: 'path', key: 'schema_id' },
                    { key: 'apiShieldSchemaEdit', map: 'body' }
                ] }]);
        return (options?.client ?? client).patch<SchemaValidationEditSchemaResponses, SchemaValidationEditSchemaErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zSchemaValidationEditSchemaBody,
                path: zSchemaValidationEditSchemaPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zSchemaValidationEditSchemaResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/schema_validation/schemas/{schema_id}',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Retrieve all operations from the schema.
     *
     * Retrieves all operations from the schema. Operations that already exist in API Shield Endpoint Management will be returned as full operations.
     */
    public static schemaValidationExtractOperationsFromSchema<ThrowOnError extends boolean = true>(parameters: {
        zone_id: ApiShieldSchemasIdentifier;
        schema_id: ApiShieldSchemasUuidWritable & string;
        feature?: Array<'thresholds' | 'parameter_schemas' | 'schema_info'>;
        host?: Array<string>;
        method?: Array<string>;
        endpoint?: string;
        page?: number;
        per_page?: number;
        operation_status?: 'new' | 'existing';
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'zone_id' },
                    { in: 'path', key: 'schema_id' },
                    { in: 'query', key: 'feature' },
                    { in: 'query', key: 'host' },
                    { in: 'query', key: 'method' },
                    { in: 'query', key: 'endpoint' },
                    { in: 'query', key: 'page' },
                    { in: 'query', key: 'per_page' },
                    { in: 'query', key: 'operation_status' }
                ] }]);
        return (options?.client ?? client).get<SchemaValidationExtractOperationsFromSchemaResponses, SchemaValidationExtractOperationsFromSchemaErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zSchemaValidationExtractOperationsFromSchemaPath,
                query: zSchemaValidationExtractOperationsFromSchemaQuery.optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zSchemaValidationExtractOperationsFromSchemaResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/schema_validation/schemas/{schema_id}/operations',
            ...options,
            ...params
        });
    }
}
