/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { IamAccountIdentifierWritable, ScimResourceTypesGetErrors, ScimResourceTypesGetResponses, ScimResourceTypesListErrors, ScimResourceTypesListResponses, ScimSchemasGetErrors, ScimSchemasGetResponses, ScimSchemasListErrors, ScimSchemasListResponses, ScimServiceProviderConfigGetErrors, ScimServiceProviderConfigGetResponses } from '../types.gen';
import { zScimResourceTypesGetPath, zScimResourceTypesGetResponse, zScimResourceTypesListPath, zScimResourceTypesListResponse, zScimSchemasGetPath, zScimSchemasGetResponse, zScimSchemasListPath, zScimSchemasListResponse, zScimServiceProviderConfigGetPath, zScimServiceProviderConfigGetResponse } from '../zod.gen';

export class ScimDiscoveryService {
    /**
     * List SCIM Resource Types
     *
     * Returns the list of SCIM resource types supported by the Cloudflare SCIM service (RFC 7643 Section 6, RFC 7644 Section 4). Clients use this to discover available resource categories (e.g. Users, Groups) and their associated schemas. Query parameters are not supported on this endpoint.
     *
     */
    public static scimResourceTypesList<ThrowOnError extends boolean = true>(parameters: {
        account_id: IamAccountIdentifierWritable;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'account_id' }] }]);
        return (options?.client ?? client).get<ScimResourceTypesListResponses, ScimResourceTypesListErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zScimResourceTypesListPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zScimResourceTypesListResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/accounts/{account_id}/scim/v2/ResourceTypes',
            ...options,
            ...params
        });
    }
    
    /**
     * Get SCIM Resource Type
     *
     * Returns a single SCIM resource type by ID (RFC 7643 Section 6). Valid IDs are `User` and `Group`.
     *
     */
    public static scimResourceTypesGet<ThrowOnError extends boolean = true>(parameters: {
        account_id: IamAccountIdentifierWritable;
        resource_type_id: 'User' | 'Group';
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'account_id' }, { in: 'path', key: 'resource_type_id' }] }]);
        return (options?.client ?? client).get<ScimResourceTypesGetResponses, ScimResourceTypesGetErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zScimResourceTypesGetPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zScimResourceTypesGetResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/accounts/{account_id}/scim/v2/ResourceTypes/{resource_type_id}',
            ...options,
            ...params
        });
    }
    
    /**
     * List SCIM Schemas
     *
     * Returns the list of SCIM schemas supported by the Cloudflare SCIM service (RFC 7643 Section 7, RFC 7644 Section 4). Clients use this to introspect the attributes of each resource type. Query parameters are not supported on this endpoint.
     *
     */
    public static scimSchemasList<ThrowOnError extends boolean = true>(parameters: {
        account_id: IamAccountIdentifierWritable;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'account_id' }] }]);
        return (options?.client ?? client).get<ScimSchemasListResponses, ScimSchemasListErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zScimSchemasListPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zScimSchemasListResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/accounts/{account_id}/scim/v2/Schemas',
            ...options,
            ...params
        });
    }
    
    /**
     * Get SCIM Schema
     *
     * Returns a single SCIM schema definition by schema URI ID (RFC 7643 Section 7). Valid IDs are `urn:ietf:params:scim:schemas:core:2.0:User` and `urn:ietf:params:scim:schemas:core:2.0:Group`.
     *
     */
    public static scimSchemasGet<ThrowOnError extends boolean = true>(parameters: {
        account_id: IamAccountIdentifierWritable;
        schema_id: string;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'account_id' }, { in: 'path', key: 'schema_id' }] }]);
        return (options?.client ?? client).get<ScimSchemasGetResponses, ScimSchemasGetErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zScimSchemasGetPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zScimSchemasGetResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/accounts/{account_id}/scim/v2/Schemas/{schema_id}',
            ...options,
            ...params
        });
    }
    
    /**
     * Get SCIM Service Provider Config
     *
     * Returns the SCIM 2.0 Service Provider configuration (RFC 7643 Section 5). IdPs use this endpoint to auto-configure their SCIM integration with Cloudflare, discovering which optional features (patch, bulk, filter, etc.) are supported.
     *
     */
    public static scimServiceProviderConfigGet<ThrowOnError extends boolean = true>(parameters: {
        account_id: IamAccountIdentifierWritable;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'account_id' }] }]);
        return (options?.client ?? client).get<ScimServiceProviderConfigGetResponses, ScimServiceProviderConfigGetErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zScimServiceProviderConfigGetPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zScimServiceProviderConfigGetResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/accounts/{account_id}/scim/v2/ServiceProviderConfig',
            ...options,
            ...params
        });
    }
}
