/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { GetSecurityCenterAccountScansErrors, GetSecurityCenterAccountScansResponses, GetSecurityCenterZoneScansErrors, GetSecurityCenterZoneScansResponses, SecurityCenterIdentifier, SecurityCenterNewScanRequest, StartSecurityCenterAccountScanErrors, StartSecurityCenterAccountScanResponses, StartSecurityCenterZoneScanErrors, StartSecurityCenterZoneScanResponses } from '../types.gen';
import { zGetSecurityCenterAccountScansPath, zGetSecurityCenterAccountScansResponse, zGetSecurityCenterZoneScansPath, zGetSecurityCenterZoneScansResponse, zStartSecurityCenterAccountScanBody, zStartSecurityCenterAccountScanPath, zStartSecurityCenterAccountScanResponse, zStartSecurityCenterZoneScanBody, zStartSecurityCenterZoneScanPath, zStartSecurityCenterZoneScanResponse } from '../zod.gen';

export class SecurityCenterScansService {
    /**
     * Get Recent Account Scans
     *
     * Returns the most recent on-demand scans for the account, up to a maximum of 5. Each scan includes its ID, start time, and current status. This includes both account-wide and zone-scoped scans.
     */
    public static getSecurityCenterAccountScans<ThrowOnError extends boolean = true>(parameters: {
        account_id: SecurityCenterIdentifier;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'account_id' }] }]);
        return (options?.client ?? client).get<GetSecurityCenterAccountScansResponses, GetSecurityCenterAccountScansErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zGetSecurityCenterAccountScansPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zGetSecurityCenterAccountScansResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/accounts/{account_id}/security-center/insights/scans',
            ...options,
            ...params
        });
    }
    
    /**
     * Start On-Demand Account Scan
     *
     * Initiates an on-demand security scan for the entire account, scanning all zones associated with the account. Rate limited to 5 scans per account per 24-hour window.
     */
    public static startSecurityCenterAccountScan<ThrowOnError extends boolean = true>(parameters: {
        account_id: SecurityCenterIdentifier;
        securityCenterNewScanRequest: SecurityCenterNewScanRequest;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'account_id' }, { key: 'securityCenterNewScanRequest', map: 'body' }] }]);
        return (options?.client ?? client).post<StartSecurityCenterAccountScanResponses, StartSecurityCenterAccountScanErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zStartSecurityCenterAccountScanBody,
                path: zStartSecurityCenterAccountScanPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zStartSecurityCenterAccountScanResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/accounts/{account_id}/security-center/insights/scans',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Get Recent Zone Scans
     *
     * Returns the most recent on-demand scans for a specific zone, up to a maximum of 5. Each scan includes its ID, start time, and current status.
     */
    public static getSecurityCenterZoneScans<ThrowOnError extends boolean = true>(parameters: {
        zone_id: SecurityCenterIdentifier;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }] }]);
        return (options?.client ?? client).get<GetSecurityCenterZoneScansResponses, GetSecurityCenterZoneScansErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zGetSecurityCenterZoneScansPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zGetSecurityCenterZoneScansResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/zones/{zone_id}/security-center/insights/scans',
            ...options,
            ...params
        });
    }
    
    /**
     * Start On-Demand Zone Scan
     *
     * Initiates an on-demand security scan for a specific zone. Rate limited to 5 scans per account per 24-hour window (shared with account-level scans).
     */
    public static startSecurityCenterZoneScan<ThrowOnError extends boolean = true>(parameters: {
        zone_id: SecurityCenterIdentifier;
        securityCenterNewScanRequest: SecurityCenterNewScanRequest;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }, { key: 'securityCenterNewScanRequest', map: 'body' }] }]);
        return (options?.client ?? client).post<StartSecurityCenterZoneScanResponses, StartSecurityCenterZoneScanErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zStartSecurityCenterZoneScanBody,
                path: zStartSecurityCenterZoneScanPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zStartSecurityCenterZoneScanResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/zones/{zone_id}/security-center/insights/scans',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
}
