/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { BeginSsoConnectorVerificationErrors, BeginSsoConnectorVerificationResponses, DeleteSsoConnectorErrors, DeleteSsoConnectorResponses, GetAllSsoConnectorsErrors, GetAllSsoConnectorsResponses, GetSsoConnectorErrors, GetSsoConnectorResponses, IamAccountIdentifierWritable, IamSsoConnectorIdentifierWritable, IamUseFedrampLanguage, InitNewSsoConnectorErrors, InitNewSsoConnectorResponses, UpdateSsoConnectorStateErrors, UpdateSsoConnectorStateResponses } from '../types.gen';
import { zBeginSsoConnectorVerificationPath, zBeginSsoConnectorVerificationResponse, zDeleteSsoConnectorPath, zDeleteSsoConnectorResponse, zGetAllSsoConnectorsPath, zGetAllSsoConnectorsResponse, zGetSsoConnectorPath, zGetSsoConnectorResponse, zInitNewSsoConnectorBody, zInitNewSsoConnectorPath, zInitNewSsoConnectorResponse, zUpdateSsoConnectorStateBody, zUpdateSsoConnectorStatePath, zUpdateSsoConnectorStateResponse } from '../zod.gen';

export class SsoService {
    /**
     * Get all SSO connectors
     */
    public static getAllSsoConnectors<ThrowOnError extends boolean = true>(parameters: {
        account_id: IamAccountIdentifierWritable;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'account_id' }] }]);
        return (options?.client ?? client).get<GetAllSsoConnectorsResponses, GetAllSsoConnectorsErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zGetAllSsoConnectorsPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zGetAllSsoConnectorsResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/accounts/{account_id}/sso_connectors',
            ...options,
            ...params
        });
    }
    
    /**
     * Initialize new SSO connector
     */
    public static initNewSsoConnector<ThrowOnError extends boolean = true>(parameters: {
        account_id: IamAccountIdentifierWritable;
        begin_verification?: boolean;
        email_domain: string;
        use_fedramp_language?: IamUseFedrampLanguage;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'account_id' },
                    { in: 'body', key: 'begin_verification' },
                    { in: 'body', key: 'email_domain' },
                    { in: 'body', key: 'use_fedramp_language' }
                ] }]);
        return (options?.client ?? client).post<InitNewSsoConnectorResponses, InitNewSsoConnectorErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zInitNewSsoConnectorBody.optional(),
                path: zInitNewSsoConnectorPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zInitNewSsoConnectorResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/accounts/{account_id}/sso_connectors',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Delete SSO connector
     */
    public static deleteSsoConnector<ThrowOnError extends boolean = true>(parameters: {
        account_id: IamAccountIdentifierWritable;
        sso_connector_id: IamSsoConnectorIdentifierWritable;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'account_id' }, { in: 'path', key: 'sso_connector_id' }] }]);
        return (options?.client ?? client).delete<DeleteSsoConnectorResponses, DeleteSsoConnectorErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zDeleteSsoConnectorPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zDeleteSsoConnectorResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/accounts/{account_id}/sso_connectors/{sso_connector_id}',
            ...options,
            ...params
        });
    }
    
    /**
     * Get single SSO connector
     */
    public static getSsoConnector<ThrowOnError extends boolean = true>(parameters: {
        account_id: IamAccountIdentifierWritable;
        sso_connector_id: IamSsoConnectorIdentifierWritable;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'account_id' }, { in: 'path', key: 'sso_connector_id' }] }]);
        return (options?.client ?? client).get<GetSsoConnectorResponses, GetSsoConnectorErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zGetSsoConnectorPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zGetSsoConnectorResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/accounts/{account_id}/sso_connectors/{sso_connector_id}',
            ...options,
            ...params
        });
    }
    
    /**
     * Update SSO connector state
     */
    public static updateSsoConnectorState<ThrowOnError extends boolean = true>(parameters: {
        account_id: IamAccountIdentifierWritable;
        sso_connector_id: IamSsoConnectorIdentifierWritable;
        enabled?: boolean;
        use_fedramp_language?: IamUseFedrampLanguage;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'account_id' },
                    { in: 'path', key: 'sso_connector_id' },
                    { in: 'body', key: 'enabled' },
                    { in: 'body', key: 'use_fedramp_language' }
                ] }]);
        return (options?.client ?? client).patch<UpdateSsoConnectorStateResponses, UpdateSsoConnectorStateErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zUpdateSsoConnectorStateBody.optional(),
                path: zUpdateSsoConnectorStatePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zUpdateSsoConnectorStateResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/accounts/{account_id}/sso_connectors/{sso_connector_id}',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Begin SSO connector verification
     */
    public static beginSsoConnectorVerification<ThrowOnError extends boolean = true>(parameters: {
        account_id: IamAccountIdentifierWritable;
        sso_connector_id: IamSsoConnectorIdentifierWritable;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'account_id' }, { in: 'path', key: 'sso_connector_id' }] }]);
        return (options?.client ?? client).post<BeginSsoConnectorVerificationResponses, BeginSsoConnectorVerificationErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zBeginSsoConnectorVerificationPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zBeginSsoConnectorVerificationResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/accounts/{account_id}/sso_connectors/{sso_connector_id}/begin_verification',
            ...options,
            ...params
        });
    }
}
