/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { ListTablesErrors, ListTablesResponses, R2DataCatalogAccountId, R2DataCatalogBucketName } from '../types.gen';
import { zListTablesPath, zListTablesQuery, zListTablesResponse } from '../zod.gen';

export class TableManagementService {
    /**
     * List tables in namespace
     *
     * Returns a list of tables in the specified namespace within an R2 catalog.
     * Supports pagination for efficient traversal of large table collections.
     *
     */
    public static listTables<ThrowOnError extends boolean = true>(parameters: {
        account_id: R2DataCatalogAccountId;
        bucket_name: R2DataCatalogBucketName;
        namespace: string;
        page_token?: string;
        page_size?: number;
        return_uuids?: boolean;
        return_details?: boolean;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'account_id' },
                    { in: 'path', key: 'bucket_name' },
                    { in: 'path', key: 'namespace' },
                    { in: 'query', key: 'page_token' },
                    { in: 'query', key: 'page_size' },
                    { in: 'query', key: 'return_uuids' },
                    { in: 'query', key: 'return_details' }
                ] }]);
        return (options?.client ?? client).get<ListTablesResponses, ListTablesErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zListTablesPath,
                query: zListTablesQuery.optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zListTablesResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/accounts/{account_id}/r2-catalog/{bucket_name}/namespaces/{namespace}/tables',
            ...options,
            ...params
        });
    }
}
