/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { CacheRulesIdentifier, CacheRulesPatch, TieredCachingGetTieredCachingSettingErrors, TieredCachingGetTieredCachingSettingResponses, TieredCachingPatchTieredCachingSettingErrors, TieredCachingPatchTieredCachingSettingResponses } from '../types.gen';
import { zTieredCachingGetTieredCachingSettingPath, zTieredCachingGetTieredCachingSettingResponse, zTieredCachingPatchTieredCachingSettingBody, zTieredCachingPatchTieredCachingSettingPath, zTieredCachingPatchTieredCachingSettingResponse } from '../zod.gen';

export class TieredCachingService {
    /**
     * Get Tiered Caching setting
     *
     * Tiered Cache works by dividing Cloudflare's data centers into a hierarchy of lower-tiers and upper-tiers. If content is not cached in lower-tier data centers (generally the ones closest to a visitor), the lower-tier must ask an upper-tier to see if it has the content. If the upper-tier does not have the content, only the upper-tier can ask the origin for content. This practice improves bandwidth efficiency by limiting the number of data centers that can ask the origin for content, which reduces origin load and makes websites more cost-effective to operate. Additionally, Tiered Cache concentrates connections to origin servers so they come from a small number of data centers rather than the full set of network locations. This results in fewer open connections using server resources.
     */
    public static tieredCachingGetTieredCachingSetting<ThrowOnError extends boolean = true>(parameters: {
        zone_id: CacheRulesIdentifier;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }] }]);
        return (options?.client ?? client).get<TieredCachingGetTieredCachingSettingResponses, TieredCachingGetTieredCachingSettingErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zTieredCachingGetTieredCachingSettingPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zTieredCachingGetTieredCachingSettingResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/argo/tiered_caching',
            ...options,
            ...params
        });
    }
    
    /**
     * Patch Tiered Caching setting
     *
     * Tiered Cache works by dividing Cloudflare's data centers into a hierarchy of lower-tiers and upper-tiers. If content is not cached in lower-tier data centers (generally the ones closest to a visitor), the lower-tier must ask an upper-tier to see if it has the content. If the upper-tier does not have the content, only the upper-tier can ask the origin for content. This practice improves bandwidth efficiency by limiting the number of data centers that can ask the origin for content, which reduces origin load and makes websites more cost-effective to operate. Additionally, Tiered Cache concentrates connections to origin servers so they come from a small number of data centers rather than the full set of network locations. This results in fewer open connections using server resources.
     */
    public static tieredCachingPatchTieredCachingSetting<ThrowOnError extends boolean = true>(parameters: {
        zone_id: CacheRulesIdentifier;
        cacheRulesPatch: CacheRulesPatch;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }, { key: 'cacheRulesPatch', map: 'body' }] }]);
        return (options?.client ?? client).patch<TieredCachingPatchTieredCachingSettingResponses, TieredCachingPatchTieredCachingSettingErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zTieredCachingPatchTieredCachingSettingBody,
                path: zTieredCachingPatchTieredCachingSettingPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zTieredCachingPatchTieredCachingSettingResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/argo/tiered_caching',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
}
