/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { ApiShieldAction, ApiShieldBulkCreateRules, ApiShieldBulkEditRules, ApiShieldCreateRule, ApiShieldEditRule, ApiShieldEnabled, ApiShieldEndpoint, ApiShieldHost, ApiShieldMethod, ApiShieldPreviewRules, ApiShieldSchemasIdentifier, ApiShieldSchemasUuidWritable, ApiShieldSelectorOperationState, TokenValidationRulesBulkCreateErrors, TokenValidationRulesBulkCreateResponses, TokenValidationRulesBulkEditErrors, TokenValidationRulesBulkEditResponses, TokenValidationRulesCreateErrors, TokenValidationRulesCreateResponses, TokenValidationRulesDeleteErrors, TokenValidationRulesDeleteResponses, TokenValidationRulesEditErrors, TokenValidationRulesEditResponses, TokenValidationRulesGetErrors, TokenValidationRulesGetResponses, TokenValidationRulesListErrors, TokenValidationRulesListResponses, TokenValidationRulesPreviewErrors, TokenValidationRulesPreviewResponses } from '../types.gen';
import { zTokenValidationRulesBulkCreateBody, zTokenValidationRulesBulkCreatePath, zTokenValidationRulesBulkCreateResponse, zTokenValidationRulesBulkEditBody, zTokenValidationRulesBulkEditPath, zTokenValidationRulesBulkEditResponse, zTokenValidationRulesCreateBody, zTokenValidationRulesCreatePath, zTokenValidationRulesCreateResponse, zTokenValidationRulesDeletePath, zTokenValidationRulesDeleteResponse, zTokenValidationRulesEditBody, zTokenValidationRulesEditPath, zTokenValidationRulesEditResponse, zTokenValidationRulesGetPath, zTokenValidationRulesGetResponse, zTokenValidationRulesListPath, zTokenValidationRulesListQuery, zTokenValidationRulesListResponse, zTokenValidationRulesPreviewBody, zTokenValidationRulesPreviewPath, zTokenValidationRulesPreviewQuery, zTokenValidationRulesPreviewResponse } from '../zod.gen';

export class TokenValidationTokenRulesService {
    /**
     * List token validation rules
     *
     * List token validation rules
     */
    public static tokenValidationRulesList<ThrowOnError extends boolean = true>(parameters: {
        zone_id: ApiShieldSchemasIdentifier;
        per_page?: number;
        page?: number;
        token_configuration?: Array<ApiShieldSchemasUuidWritable>;
        action?: ApiShieldAction;
        enabled?: ApiShieldEnabled;
        id?: ApiShieldSchemasUuidWritable;
        rule_id?: ApiShieldSchemasUuidWritable;
        host?: ApiShieldHost;
        hostname?: ApiShieldHost;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'zone_id' },
                    { in: 'query', key: 'per_page' },
                    { in: 'query', key: 'page' },
                    { in: 'query', key: 'token_configuration' },
                    { in: 'query', key: 'action' },
                    { in: 'query', key: 'enabled' },
                    { in: 'query', key: 'id' },
                    { in: 'query', key: 'rule_id' },
                    { in: 'query', key: 'host' },
                    { in: 'query', key: 'hostname' }
                ] }]);
        return (options?.client ?? client).get<TokenValidationRulesListResponses, TokenValidationRulesListErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zTokenValidationRulesListPath,
                query: zTokenValidationRulesListQuery.optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zTokenValidationRulesListResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/token_validation/rules',
            ...options,
            ...params
        });
    }
    
    /**
     * Create a token validation rule
     *
     * Create a token validation rule.
     */
    public static tokenValidationRulesCreate<ThrowOnError extends boolean = true>(parameters: {
        zone_id: ApiShieldSchemasIdentifier;
        apiShieldCreateRule: ApiShieldCreateRule;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }, { key: 'apiShieldCreateRule', map: 'body' }] }]);
        return (options?.client ?? client).post<TokenValidationRulesCreateResponses, TokenValidationRulesCreateErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zTokenValidationRulesCreateBody,
                path: zTokenValidationRulesCreatePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zTokenValidationRulesCreateResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/token_validation/rules',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Bulk edit token validation rules
     *
     * Edit token validation rules.
     *
     * A request can update multiple Token Validation Rules.
     *
     * Rules can be re-ordered using the `position` field.
     *
     * Returns all updated rules.
     *
     */
    public static tokenValidationRulesBulkEdit<ThrowOnError extends boolean = true>(parameters: {
        zone_id: ApiShieldSchemasIdentifier;
        apiShieldBulkEditRules: ApiShieldBulkEditRules;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }, { key: 'apiShieldBulkEditRules', map: 'body' }] }]);
        return (options?.client ?? client).patch<TokenValidationRulesBulkEditResponses, TokenValidationRulesBulkEditErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zTokenValidationRulesBulkEditBody,
                path: zTokenValidationRulesBulkEditPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zTokenValidationRulesBulkEditResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/token_validation/rules/bulk',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Bulk create token validation rules
     *
     * Create zone token validation rules.
     *
     * A request can create multiple Token Validation Rules.
     *
     */
    public static tokenValidationRulesBulkCreate<ThrowOnError extends boolean = true>(parameters: {
        zone_id: ApiShieldSchemasIdentifier;
        apiShieldBulkCreateRules: ApiShieldBulkCreateRules;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }, { key: 'apiShieldBulkCreateRules', map: 'body' }] }]);
        return (options?.client ?? client).post<TokenValidationRulesBulkCreateResponses, TokenValidationRulesBulkCreateErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zTokenValidationRulesBulkCreateBody,
                path: zTokenValidationRulesBulkCreatePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zTokenValidationRulesBulkCreateResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/token_validation/rules/bulk',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Preview operations covered by a Token Validation rule
     *
     * Preview operations covered by a Token Validation rule.
     *
     * The API will return all operations on a zone annotated with an additional `state` field.
     * Operations with an `included` `state` will be covered by a Token Validation Rule.
     *
     */
    public static tokenValidationRulesPreview<ThrowOnError extends boolean = true>(parameters: {
        zone_id: ApiShieldSchemasIdentifier;
        per_page?: number;
        page?: number;
        state?: Array<ApiShieldSelectorOperationState>;
        host?: Array<ApiShieldHost>;
        hostname?: Array<ApiShieldHost>;
        method?: Array<ApiShieldMethod>;
        endpoint?: Array<ApiShieldEndpoint>;
        apiShieldPreviewRules: ApiShieldPreviewRules;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'zone_id' },
                    { in: 'query', key: 'per_page' },
                    { in: 'query', key: 'page' },
                    { in: 'query', key: 'state' },
                    { in: 'query', key: 'host' },
                    { in: 'query', key: 'hostname' },
                    { in: 'query', key: 'method' },
                    { in: 'query', key: 'endpoint' },
                    { key: 'apiShieldPreviewRules', map: 'body' }
                ] }]);
        return (options?.client ?? client).post<TokenValidationRulesPreviewResponses, TokenValidationRulesPreviewErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zTokenValidationRulesPreviewBody,
                path: zTokenValidationRulesPreviewPath,
                query: zTokenValidationRulesPreviewQuery.optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zTokenValidationRulesPreviewResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/token_validation/rules/preview',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Delete a zone token validation rule
     *
     * Delete a zone token validation rule.
     */
    public static tokenValidationRulesDelete<ThrowOnError extends boolean = true>(parameters: {
        zone_id: ApiShieldSchemasIdentifier;
        rule_id: ApiShieldSchemasUuidWritable;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }, { in: 'path', key: 'rule_id' }] }]);
        return (options?.client ?? client).delete<TokenValidationRulesDeleteResponses, TokenValidationRulesDeleteErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zTokenValidationRulesDeletePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zTokenValidationRulesDeleteResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/token_validation/rules/{rule_id}',
            ...options,
            ...params
        });
    }
    
    /**
     * Get a zone token validation rule
     *
     * Get a zone token validation rule.
     */
    public static tokenValidationRulesGet<ThrowOnError extends boolean = true>(parameters: {
        zone_id: ApiShieldSchemasIdentifier;
        rule_id: ApiShieldSchemasUuidWritable;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }, { in: 'path', key: 'rule_id' }] }]);
        return (options?.client ?? client).get<TokenValidationRulesGetResponses, TokenValidationRulesGetErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zTokenValidationRulesGetPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zTokenValidationRulesGetResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/token_validation/rules/{rule_id}',
            ...options,
            ...params
        });
    }
    
    /**
     * Edit a zone token validation rule
     *
     * Edit a zone token validation rule.
     */
    public static tokenValidationRulesEdit<ThrowOnError extends boolean = true>(parameters: {
        zone_id: ApiShieldSchemasIdentifier;
        rule_id: ApiShieldSchemasUuidWritable;
        apiShieldEditRule: ApiShieldEditRule;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'zone_id' },
                    { in: 'path', key: 'rule_id' },
                    { key: 'apiShieldEditRule', map: 'body' }
                ] }]);
        return (options?.client ?? client).patch<TokenValidationRulesEditResponses, TokenValidationRulesEditErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zTokenValidationRulesEditBody,
                path: zTokenValidationRulesEditPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zTokenValidationRulesEditResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/zones/{zone_id}/token_validation/rules/{rule_id}',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
}
