/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { TlsCertificatesAndHostnamesIdentifier, TlsCertificatesAndHostnamesUniversal, UniversalSslSettingsForAZoneEditUniversalSslSettingsErrors, UniversalSslSettingsForAZoneEditUniversalSslSettingsResponses, UniversalSslSettingsForAZoneUniversalSslSettingsDetailsErrors, UniversalSslSettingsForAZoneUniversalSslSettingsDetailsResponses } from '../types.gen';
import { zUniversalSslSettingsForAZoneEditUniversalSslSettingsBody, zUniversalSslSettingsForAZoneEditUniversalSslSettingsPath, zUniversalSslSettingsForAZoneEditUniversalSslSettingsResponse, zUniversalSslSettingsForAZoneUniversalSslSettingsDetailsPath, zUniversalSslSettingsForAZoneUniversalSslSettingsDetailsResponse } from '../zod.gen';

export class UniversalSslSettingsForAZoneService {
    /**
     * Universal SSL Settings Details
     *
     * Get Universal SSL Settings for a Zone.
     */
    public static universalSslSettingsForAZoneUniversalSslSettingsDetails<ThrowOnError extends boolean = true>(parameters: {
        zone_id: TlsCertificatesAndHostnamesIdentifier;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }] }]);
        return (options?.client ?? client).get<UniversalSslSettingsForAZoneUniversalSslSettingsDetailsResponses, UniversalSslSettingsForAZoneUniversalSslSettingsDetailsErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zUniversalSslSettingsForAZoneUniversalSslSettingsDetailsPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zUniversalSslSettingsForAZoneUniversalSslSettingsDetailsResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/zones/{zone_id}/ssl/universal/settings',
            ...options,
            ...params
        });
    }
    
    /**
     * Edit Universal SSL Settings
     *
     * Patch Universal SSL Settings for a Zone.
     */
    public static universalSslSettingsForAZoneEditUniversalSslSettings<ThrowOnError extends boolean = true>(parameters: {
        zone_id: TlsCertificatesAndHostnamesIdentifier;
        tlsCertificatesAndHostnamesUniversal: TlsCertificatesAndHostnamesUniversal;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }, { key: 'tlsCertificatesAndHostnamesUniversal', map: 'body' }] }]);
        return (options?.client ?? client).patch<UniversalSslSettingsForAZoneEditUniversalSslSettingsResponses, UniversalSslSettingsForAZoneEditUniversalSslSettingsErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zUniversalSslSettingsForAZoneEditUniversalSslSettingsBody,
                path: zUniversalSslSettingsForAZoneEditUniversalSslSettingsPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zUniversalSslSettingsForAZoneEditUniversalSslSettingsResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/zones/{zone_id}/ssl/universal/settings',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
}
