/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import { Telemetry3 } from '../sdk.gen';

export class ValuesService {
    static telemetry = Telemetry3;
}
