/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { WafManagedRulesIdentifier, WafManagedRulesMode, WafManagedRulesSchemasIdentifier, WafRuleGroupsGetAWafRuleGroupErrors, WafRuleGroupsGetAWafRuleGroupResponses, WafRuleGroupsListWafRuleGroupsErrors, WafRuleGroupsListWafRuleGroupsResponses, WafRuleGroupsUpdateAWafRuleGroupErrors, WafRuleGroupsUpdateAWafRuleGroupResponses } from '../types.gen';
import { zWafRuleGroupsGetAWafRuleGroupPath, zWafRuleGroupsGetAWafRuleGroupResponse, zWafRuleGroupsListWafRuleGroupsPath, zWafRuleGroupsListWafRuleGroupsQuery, zWafRuleGroupsListWafRuleGroupsResponse, zWafRuleGroupsUpdateAWafRuleGroupBody, zWafRuleGroupsUpdateAWafRuleGroupPath, zWafRuleGroupsUpdateAWafRuleGroupResponse } from '../zod.gen';

export class WafRuleGroupsService {
    /**
     * List WAF rule groups
     *
     * Fetches the WAF rule groups in a WAF package.
     *
     * **Note:** Applies only to the [previous version of WAF managed rules](https://developers.cloudflare.com/support/firewall/managed-rules-web-application-firewall-waf/understanding-waf-managed-rules-web-application-firewall/).
     *
     * @deprecated
     */
    public static wafRuleGroupsListWafRuleGroups<ThrowOnError extends boolean = true>(parameters: {
        package_id: WafManagedRulesIdentifier;
        zone_id: WafManagedRulesSchemasIdentifier;
        mode?: WafManagedRulesMode;
        page?: number;
        per_page?: number;
        order?: 'mode' | 'rules_count';
        direction?: 'asc' | 'desc';
        match?: 'any' | 'all';
        name?: string;
        rules_count?: number;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'package_id' },
                    { in: 'path', key: 'zone_id' },
                    { in: 'query', key: 'mode' },
                    { in: 'query', key: 'page' },
                    { in: 'query', key: 'per_page' },
                    { in: 'query', key: 'order' },
                    { in: 'query', key: 'direction' },
                    { in: 'query', key: 'match' },
                    { in: 'query', key: 'name' },
                    { in: 'query', key: 'rules_count' }
                ] }]);
        return (options?.client ?? client).get<WafRuleGroupsListWafRuleGroupsResponses, WafRuleGroupsListWafRuleGroupsErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zWafRuleGroupsListWafRuleGroupsPath,
                query: zWafRuleGroupsListWafRuleGroupsQuery.optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zWafRuleGroupsListWafRuleGroupsResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/zones/{zone_id}/firewall/waf/packages/{package_id}/groups',
            ...options,
            ...params
        });
    }
    
    /**
     * Get a WAF rule group
     *
     * Fetches the details of a WAF rule group.
     *
     * **Note:** Applies only to the [previous version of WAF managed rules](https://developers.cloudflare.com/support/firewall/managed-rules-web-application-firewall-waf/understanding-waf-managed-rules-web-application-firewall/).
     *
     * @deprecated
     */
    public static wafRuleGroupsGetAWafRuleGroup<ThrowOnError extends boolean = true>(parameters: {
        group_id: WafManagedRulesIdentifier;
        package_id: WafManagedRulesIdentifier;
        zone_id: WafManagedRulesSchemasIdentifier;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'group_id' },
                    { in: 'path', key: 'package_id' },
                    { in: 'path', key: 'zone_id' }
                ] }]);
        return (options?.client ?? client).get<WafRuleGroupsGetAWafRuleGroupResponses, WafRuleGroupsGetAWafRuleGroupErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zWafRuleGroupsGetAWafRuleGroupPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zWafRuleGroupsGetAWafRuleGroupResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/zones/{zone_id}/firewall/waf/packages/{package_id}/groups/{group_id}',
            ...options,
            ...params
        });
    }
    
    /**
     * Update a WAF rule group
     *
     * Updates a WAF rule group. You can update the state (`mode` parameter) of a rule group.
     *
     * **Note:** Applies only to the [previous version of WAF managed rules](https://developers.cloudflare.com/support/firewall/managed-rules-web-application-firewall-waf/understanding-waf-managed-rules-web-application-firewall/).
     *
     * @deprecated
     */
    public static wafRuleGroupsUpdateAWafRuleGroup<ThrowOnError extends boolean = true>(parameters: {
        group_id: WafManagedRulesIdentifier;
        package_id: WafManagedRulesIdentifier;
        zone_id: WafManagedRulesSchemasIdentifier;
        mode?: WafManagedRulesMode;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'group_id' },
                    { in: 'path', key: 'package_id' },
                    { in: 'path', key: 'zone_id' },
                    { in: 'body', key: 'mode' }
                ] }]);
        return (options?.client ?? client).patch<WafRuleGroupsUpdateAWafRuleGroupResponses, WafRuleGroupsUpdateAWafRuleGroupErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zWafRuleGroupsUpdateAWafRuleGroupBody,
                path: zWafRuleGroupsUpdateAWafRuleGroupPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zWafRuleGroupsUpdateAWafRuleGroupResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/zones/{zone_id}/firewall/waf/packages/{package_id}/groups/{group_id}',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
}
