/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { Web3ContentListEntryCreateRequest, Web3ContentListUpdateRequestWritable, Web3CreateRequest, Web3HostnameCreateIpfsUniversalPathGatewayContentListEntryErrors, Web3HostnameCreateIpfsUniversalPathGatewayContentListEntryResponses, Web3HostnameCreateWeb3HostnameErrors, Web3HostnameCreateWeb3HostnameResponses, Web3HostnameDeleteIpfsUniversalPathGatewayContentListEntryErrors, Web3HostnameDeleteIpfsUniversalPathGatewayContentListEntryResponses, Web3HostnameDeleteWeb3HostnameErrors, Web3HostnameDeleteWeb3HostnameResponses, Web3HostnameEditIpfsUniversalPathGatewayContentListEntryErrors, Web3HostnameEditIpfsUniversalPathGatewayContentListEntryResponses, Web3HostnameEditWeb3HostnameErrors, Web3HostnameEditWeb3HostnameResponses, Web3HostnameIpfsUniversalPathGatewayContentListDetailsErrors, Web3HostnameIpfsUniversalPathGatewayContentListDetailsResponses, Web3HostnameIpfsUniversalPathGatewayContentListEntryDetailsErrors, Web3HostnameIpfsUniversalPathGatewayContentListEntryDetailsResponses, Web3HostnameListIpfsUniversalPathGatewayContentListEntriesErrors, Web3HostnameListIpfsUniversalPathGatewayContentListEntriesResponses, Web3HostnameListWeb3HostnamesErrors, Web3HostnameListWeb3HostnamesResponses, Web3HostnameUpdateIpfsUniversalPathGatewayContentListErrors, Web3HostnameUpdateIpfsUniversalPathGatewayContentListResponses, Web3HostnameWeb3HostnameDetailsErrors, Web3HostnameWeb3HostnameDetailsResponses, Web3Identifier, Web3ModifyRequest } from '../types.gen';
import { zWeb3HostnameCreateIpfsUniversalPathGatewayContentListEntryBody, zWeb3HostnameCreateIpfsUniversalPathGatewayContentListEntryPath, zWeb3HostnameCreateIpfsUniversalPathGatewayContentListEntryResponse, zWeb3HostnameCreateWeb3HostnameBody, zWeb3HostnameCreateWeb3HostnamePath, zWeb3HostnameCreateWeb3HostnameResponse, zWeb3HostnameDeleteIpfsUniversalPathGatewayContentListEntryBody, zWeb3HostnameDeleteIpfsUniversalPathGatewayContentListEntryPath, zWeb3HostnameDeleteIpfsUniversalPathGatewayContentListEntryResponse, zWeb3HostnameDeleteWeb3HostnameBody, zWeb3HostnameDeleteWeb3HostnamePath, zWeb3HostnameDeleteWeb3HostnameResponse, zWeb3HostnameEditIpfsUniversalPathGatewayContentListEntryBody, zWeb3HostnameEditIpfsUniversalPathGatewayContentListEntryPath, zWeb3HostnameEditIpfsUniversalPathGatewayContentListEntryResponse, zWeb3HostnameEditWeb3HostnameBody, zWeb3HostnameEditWeb3HostnamePath, zWeb3HostnameEditWeb3HostnameResponse, zWeb3HostnameIpfsUniversalPathGatewayContentListDetailsPath, zWeb3HostnameIpfsUniversalPathGatewayContentListDetailsResponse, zWeb3HostnameIpfsUniversalPathGatewayContentListEntryDetailsPath, zWeb3HostnameIpfsUniversalPathGatewayContentListEntryDetailsResponse, zWeb3HostnameListIpfsUniversalPathGatewayContentListEntriesPath, zWeb3HostnameListIpfsUniversalPathGatewayContentListEntriesResponse, zWeb3HostnameListWeb3HostnamesPath, zWeb3HostnameListWeb3HostnamesResponse, zWeb3HostnameUpdateIpfsUniversalPathGatewayContentListBody, zWeb3HostnameUpdateIpfsUniversalPathGatewayContentListPath, zWeb3HostnameUpdateIpfsUniversalPathGatewayContentListResponse, zWeb3HostnameWeb3HostnameDetailsPath, zWeb3HostnameWeb3HostnameDetailsResponse } from '../zod.gen';

export class Web3HostnameService {
    /**
     * List Web3 Hostnames
     */
    public static web3HostnameListWeb3Hostnames<ThrowOnError extends boolean = true>(parameters: {
        zone_id: Web3Identifier;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }] }]);
        return (options?.client ?? client).get<Web3HostnameListWeb3HostnamesResponses, Web3HostnameListWeb3HostnamesErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zWeb3HostnameListWeb3HostnamesPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zWeb3HostnameListWeb3HostnamesResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/zones/{zone_id}/web3/hostnames',
            ...options,
            ...params
        });
    }
    
    /**
     * Create Web3 Hostname
     */
    public static web3HostnameCreateWeb3Hostname<ThrowOnError extends boolean = true>(parameters: {
        zone_id: Web3Identifier;
        web3CreateRequest: Web3CreateRequest;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'zone_id' }, { key: 'web3CreateRequest', map: 'body' }] }]);
        return (options?.client ?? client).post<Web3HostnameCreateWeb3HostnameResponses, Web3HostnameCreateWeb3HostnameErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zWeb3HostnameCreateWeb3HostnameBody,
                path: zWeb3HostnameCreateWeb3HostnamePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zWeb3HostnameCreateWeb3HostnameResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/zones/{zone_id}/web3/hostnames',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Delete Web3 Hostname
     */
    public static web3HostnameDeleteWeb3Hostname<ThrowOnError extends boolean = true>(parameters: {
        identifier: Web3Identifier;
        zone_id: Web3Identifier;
        body: unknown;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'identifier' },
                    { in: 'path', key: 'zone_id' },
                    { key: 'body', map: 'body' }
                ] }]);
        return (options?.client ?? client).delete<Web3HostnameDeleteWeb3HostnameResponses, Web3HostnameDeleteWeb3HostnameErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zWeb3HostnameDeleteWeb3HostnameBody,
                path: zWeb3HostnameDeleteWeb3HostnamePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zWeb3HostnameDeleteWeb3HostnameResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/zones/{zone_id}/web3/hostnames/{identifier}',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Web3 Hostname Details
     */
    public static web3HostnameWeb3HostnameDetails<ThrowOnError extends boolean = true>(parameters: {
        identifier: Web3Identifier;
        zone_id: Web3Identifier;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'identifier' }, { in: 'path', key: 'zone_id' }] }]);
        return (options?.client ?? client).get<Web3HostnameWeb3HostnameDetailsResponses, Web3HostnameWeb3HostnameDetailsErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zWeb3HostnameWeb3HostnameDetailsPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zWeb3HostnameWeb3HostnameDetailsResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/zones/{zone_id}/web3/hostnames/{identifier}',
            ...options,
            ...params
        });
    }
    
    /**
     * Edit Web3 Hostname
     */
    public static web3HostnameEditWeb3Hostname<ThrowOnError extends boolean = true>(parameters: {
        identifier: Web3Identifier;
        zone_id: Web3Identifier;
        web3ModifyRequest: Web3ModifyRequest;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'identifier' },
                    { in: 'path', key: 'zone_id' },
                    { key: 'web3ModifyRequest', map: 'body' }
                ] }]);
        return (options?.client ?? client).patch<Web3HostnameEditWeb3HostnameResponses, Web3HostnameEditWeb3HostnameErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zWeb3HostnameEditWeb3HostnameBody,
                path: zWeb3HostnameEditWeb3HostnamePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zWeb3HostnameEditWeb3HostnameResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/zones/{zone_id}/web3/hostnames/{identifier}',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * IPFS Universal Path Gateway Content List Details
     */
    public static web3HostnameIpfsUniversalPathGatewayContentListDetails<ThrowOnError extends boolean = true>(parameters: {
        identifier: Web3Identifier;
        zone_id: Web3Identifier;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'identifier' }, { in: 'path', key: 'zone_id' }] }]);
        return (options?.client ?? client).get<Web3HostnameIpfsUniversalPathGatewayContentListDetailsResponses, Web3HostnameIpfsUniversalPathGatewayContentListDetailsErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zWeb3HostnameIpfsUniversalPathGatewayContentListDetailsPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zWeb3HostnameIpfsUniversalPathGatewayContentListDetailsResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/zones/{zone_id}/web3/hostnames/{identifier}/ipfs_universal_path/content_list',
            ...options,
            ...params
        });
    }
    
    /**
     * Update IPFS Universal Path Gateway Content List
     */
    public static web3HostnameUpdateIpfsUniversalPathGatewayContentList<ThrowOnError extends boolean = true>(parameters: {
        identifier: Web3Identifier;
        zone_id: Web3Identifier;
        web3ContentListUpdateRequestWritable: Web3ContentListUpdateRequestWritable;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'identifier' },
                    { in: 'path', key: 'zone_id' },
                    { key: 'web3ContentListUpdateRequestWritable', map: 'body' }
                ] }]);
        return (options?.client ?? client).put<Web3HostnameUpdateIpfsUniversalPathGatewayContentListResponses, Web3HostnameUpdateIpfsUniversalPathGatewayContentListErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zWeb3HostnameUpdateIpfsUniversalPathGatewayContentListBody,
                path: zWeb3HostnameUpdateIpfsUniversalPathGatewayContentListPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zWeb3HostnameUpdateIpfsUniversalPathGatewayContentListResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/zones/{zone_id}/web3/hostnames/{identifier}/ipfs_universal_path/content_list',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * List IPFS Universal Path Gateway Content List Entries
     */
    public static web3HostnameListIpfsUniversalPathGatewayContentListEntries<ThrowOnError extends boolean = true>(parameters: {
        identifier: Web3Identifier;
        zone_id: Web3Identifier;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'identifier' }, { in: 'path', key: 'zone_id' }] }]);
        return (options?.client ?? client).get<Web3HostnameListIpfsUniversalPathGatewayContentListEntriesResponses, Web3HostnameListIpfsUniversalPathGatewayContentListEntriesErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zWeb3HostnameListIpfsUniversalPathGatewayContentListEntriesPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zWeb3HostnameListIpfsUniversalPathGatewayContentListEntriesResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/zones/{zone_id}/web3/hostnames/{identifier}/ipfs_universal_path/content_list/entries',
            ...options,
            ...params
        });
    }
    
    /**
     * Create IPFS Universal Path Gateway Content List Entry
     */
    public static web3HostnameCreateIpfsUniversalPathGatewayContentListEntry<ThrowOnError extends boolean = true>(parameters: {
        identifier: Web3Identifier;
        zone_id: Web3Identifier;
        web3ContentListEntryCreateRequest: Web3ContentListEntryCreateRequest;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'identifier' },
                    { in: 'path', key: 'zone_id' },
                    { key: 'web3ContentListEntryCreateRequest', map: 'body' }
                ] }]);
        return (options?.client ?? client).post<Web3HostnameCreateIpfsUniversalPathGatewayContentListEntryResponses, Web3HostnameCreateIpfsUniversalPathGatewayContentListEntryErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zWeb3HostnameCreateIpfsUniversalPathGatewayContentListEntryBody,
                path: zWeb3HostnameCreateIpfsUniversalPathGatewayContentListEntryPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zWeb3HostnameCreateIpfsUniversalPathGatewayContentListEntryResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/zones/{zone_id}/web3/hostnames/{identifier}/ipfs_universal_path/content_list/entries',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Delete IPFS Universal Path Gateway Content List Entry
     */
    public static web3HostnameDeleteIpfsUniversalPathGatewayContentListEntry<ThrowOnError extends boolean = true>(parameters: {
        content_list_entry_identifier: Web3Identifier;
        identifier: Web3Identifier;
        zone_id: Web3Identifier;
        body: unknown;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'content_list_entry_identifier' },
                    { in: 'path', key: 'identifier' },
                    { in: 'path', key: 'zone_id' },
                    { key: 'body', map: 'body' }
                ] }]);
        return (options?.client ?? client).delete<Web3HostnameDeleteIpfsUniversalPathGatewayContentListEntryResponses, Web3HostnameDeleteIpfsUniversalPathGatewayContentListEntryErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zWeb3HostnameDeleteIpfsUniversalPathGatewayContentListEntryBody,
                path: zWeb3HostnameDeleteIpfsUniversalPathGatewayContentListEntryPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zWeb3HostnameDeleteIpfsUniversalPathGatewayContentListEntryResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/zones/{zone_id}/web3/hostnames/{identifier}/ipfs_universal_path/content_list/entries/{content_list_entry_identifier}',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * IPFS Universal Path Gateway Content List Entry Details
     */
    public static web3HostnameIpfsUniversalPathGatewayContentListEntryDetails<ThrowOnError extends boolean = true>(parameters: {
        content_list_entry_identifier: Web3Identifier;
        identifier: Web3Identifier;
        zone_id: Web3Identifier;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'content_list_entry_identifier' },
                    { in: 'path', key: 'identifier' },
                    { in: 'path', key: 'zone_id' }
                ] }]);
        return (options?.client ?? client).get<Web3HostnameIpfsUniversalPathGatewayContentListEntryDetailsResponses, Web3HostnameIpfsUniversalPathGatewayContentListEntryDetailsErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zWeb3HostnameIpfsUniversalPathGatewayContentListEntryDetailsPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zWeb3HostnameIpfsUniversalPathGatewayContentListEntryDetailsResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/zones/{zone_id}/web3/hostnames/{identifier}/ipfs_universal_path/content_list/entries/{content_list_entry_identifier}',
            ...options,
            ...params
        });
    }
    
    /**
     * Edit IPFS Universal Path Gateway Content List Entry
     */
    public static web3HostnameEditIpfsUniversalPathGatewayContentListEntry<ThrowOnError extends boolean = true>(parameters: {
        content_list_entry_identifier: Web3Identifier;
        identifier: Web3Identifier;
        zone_id: Web3Identifier;
        web3ContentListEntryCreateRequest: Web3ContentListEntryCreateRequest;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'path', key: 'content_list_entry_identifier' },
                    { in: 'path', key: 'identifier' },
                    { in: 'path', key: 'zone_id' },
                    { key: 'web3ContentListEntryCreateRequest', map: 'body' }
                ] }]);
        return (options?.client ?? client).put<Web3HostnameEditIpfsUniversalPathGatewayContentListEntryResponses, Web3HostnameEditIpfsUniversalPathGatewayContentListEntryErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zWeb3HostnameEditIpfsUniversalPathGatewayContentListEntryBody,
                path: zWeb3HostnameEditIpfsUniversalPathGatewayContentListEntryPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zWeb3HostnameEditIpfsUniversalPathGatewayContentListEntryResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/zones/{zone_id}/web3/hostnames/{identifier}/ipfs_universal_path/content_list/entries/{content_list_entry_identifier}',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
}
