/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { WorkersAiPostWebsocketRunCfPipecatAiSmartTurnV2Errors, WorkersAiPostWebsocketRunCfPipecatAiSmartTurnV3Errors, WorkersAiPostWebsocketRunCfTestHelloWorldCogErrors } from '../types.gen';
import { zWorkersAiPostWebsocketRunCfPipecatAiSmartTurnV2Path, zWorkersAiPostWebsocketRunCfPipecatAiSmartTurnV3Path, zWorkersAiPostWebsocketRunCfTestHelloWorldCogPath } from '../zod.gen';

export class WorkersAiDumbPipeService {
    /**
     * Open Websocket connection with @cf/pipecat-ai/smart-turn-v2 model.
     *
     * Opens a WebSocket connection to stream inference results from the @cf/pipecat-ai/smart-turn-v2 model.
     */
    public static workersAiPostWebsocketRunCfPipecatAiSmartTurnV2<ThrowOnError extends boolean = true>(parameters: {
        account_id: string;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'account_id' }] }]);
        return (options?.client ?? client).get<unknown, WorkersAiPostWebsocketRunCfPipecatAiSmartTurnV2Errors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zWorkersAiPostWebsocketRunCfPipecatAiSmartTurnV2Path,
                query: z.never().optional()
            }).parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/accounts/{account_id}/ai/run/@cf/pipecat-ai/smart-turn-v2',
            ...options,
            ...params
        });
    }
    
    /**
     * Open Websocket connection with @cf/pipecat-ai/smart-turn-v3 model.
     *
     * Opens a WebSocket connection to stream inference results from the @cf/pipecat-ai/smart-turn-v3 model.
     */
    public static workersAiPostWebsocketRunCfPipecatAiSmartTurnV3<ThrowOnError extends boolean = true>(parameters: {
        account_id: string;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'account_id' }] }]);
        return (options?.client ?? client).get<unknown, WorkersAiPostWebsocketRunCfPipecatAiSmartTurnV3Errors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zWorkersAiPostWebsocketRunCfPipecatAiSmartTurnV3Path,
                query: z.never().optional()
            }).parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/accounts/{account_id}/ai/run/@cf/pipecat-ai/smart-turn-v3',
            ...options,
            ...params
        });
    }
    
    /**
     * Open Websocket connection with @cf/test/hello-world-cog model.
     *
     * Opens a WebSocket connection to stream inference results from the @cf/test/hello-world-cog model.
     */
    public static workersAiPostWebsocketRunCfTestHelloWorldCog<ThrowOnError extends boolean = true>(parameters: {
        account_id: string;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'account_id' }] }]);
        return (options?.client ?? client).get<unknown, WorkersAiPostWebsocketRunCfTestHelloWorldCogErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zWorkersAiPostWebsocketRunCfTestHelloWorldCogPath,
                query: z.never().optional()
            }).parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' }
            ],
            url: '/accounts/{account_id}/ai/run/@cf/test/hello-world-cog',
            ...options,
            ...params
        });
    }
}
