/* eslint-disable -- This file is auto-generated by @hey-api/openapi-ts */
// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { buildClientParams } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { AccessSchemasIdentifierWritable, AccessSeatsDefinition, ZeroTrustSeatsUpdateAuserSeatErrors, ZeroTrustSeatsUpdateAuserSeatResponses } from '../types.gen';
import { zZeroTrustSeatsUpdateAuserSeatBody, zZeroTrustSeatsUpdateAuserSeatPath, zZeroTrustSeatsUpdateAuserSeatResponse } from '../zod.gen';

export class ZeroTrustSeatsService {
    /**
     * Update a user seat
     *
     * Removes a user from a Zero Trust seat when both `access_seat` and `gateway_seat` are set to false.
     */
    public static zeroTrustSeatsUpdateAUserSeat<ThrowOnError extends boolean = true>(parameters: {
        account_id: AccessSchemasIdentifierWritable;
        accessSeatsDefinition: AccessSeatsDefinition;
    }, options?: Options<never, ThrowOnError>) {
        const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'account_id' }, { key: 'accessSeatsDefinition', map: 'body' }] }]);
        return (options?.client ?? client).patch<ZeroTrustSeatsUpdateAuserSeatResponses, ZeroTrustSeatsUpdateAuserSeatErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zZeroTrustSeatsUpdateAuserSeatBody,
                path: zZeroTrustSeatsUpdateAuserSeatPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zZeroTrustSeatsUpdateAuserSeatResponse.parseAsync(data),
            security: [
                { name: 'X-Auth-Email', type: 'apiKey' },
                { name: 'X-Auth-Key', type: 'apiKey' },
                { scheme: 'bearer', type: 'http' }
            ],
            url: '/accounts/{account_id}/access/seats',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
}
